import Mathlib
import Nodes.«erdos-402--h3-v2--h1--h1--h1».Context

open Filter

/-! Hole `hmid` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_402__h3_v2__h1__h1__h1 : ∀ (B : Finset ℕ),
  (0 : ℕ) ∉ B →
    B.Nonempty →
      B.gcd id = (1 : ℕ) →
        ¬Nat.Prime B.card →
          (∀ (q : ℕ), Nat.Prime q → B.card ≠ q + (1 : ℕ)) →
            (∀ a ∈ B, ∀ b ∈ B, a ≤ B.card * a.gcd b) →
              (∀ a ∈ B, ∀ (p k : ℕ), Nat.Prime p → p ^ k ∣ a → p ^ k < B.card) →
                (∃ a ∈ B, ∃ b ∈ B, (↑(a.gcd b) : ℚ) ≤ (↑a : ℚ) / (↑B.card : ℚ)) ∨
                  ∃ (p : ℕ), Nat.Prime p ∧ B.card ≤ (3 : ℕ) * p ∧ ∃ a ∈ B, p ∣ a := by
  -- Informal argument: the annex appended to this node on 2026-10-01 by this pseudonym (agent 402-R5-a), "window-prime criterion".
  -- Lean of the assembly: agent 402-R4-c (clean-room; engineering/evidence/testers-2026-10-01/402-R4-c), re-verified by 402-R5-a.
  -- Hole `hwin`: under this node's hypotheses, B has a pair with gcd(a, b) ≤ a / n, or there is a prime p with
  -- n < p < 2n and (2n − p)² ≤ n (n = |B|). The assembly proves that such a prime forces a pair.
  have hwin : ∀ (B : Finset ℕ),
    (0 : ℕ) ∉ B →
      B.Nonempty →
        B.gcd id = (1 : ℕ) →
          ¬Nat.Prime B.card →
            (∀ (q : ℕ), Nat.Prime q → B.card ≠ q + (1 : ℕ)) →
              (∀ a ∈ B, ∀ b ∈ B, a ≤ B.card * a.gcd b) →
                (∀ a ∈ B, ∀ (p k : ℕ), Nat.Prime p → p ^ k ∣ a → p ^ k < B.card) →
                  (∃ a ∈ B, ∃ b ∈ B, (↑(a.gcd b) : ℚ) ≤ (↑a : ℚ) / (↑B.card : ℚ)) ∨
                    ∃ (p : ℕ), Nat.Prime p ∧ B.card < p ∧ p < 2 * B.card ∧
                    (2 * B.card - p) * (2 * B.card - p) ≤ B.card := by
    -- Second step of the window-prime route (402-R5-a). Holes: `hres` (the seven sizes with no window prime),
    -- `hlarge` (sizes above 200014; analytic, see the node's annex), `hw1`..`hw18` (window primes for 681..200014,
    -- finite certificates). The assembly proves the window primes for 2..680 and the case split.
    have hall : (∀ (B : Finset ℕ),
      (0 : ℕ) ∉ B →
        B.Nonempty →
          B.gcd id = (1 : ℕ) →
            ¬Nat.Prime B.card →
              (∀ (q : ℕ), Nat.Prime q → B.card ≠ q + (1 : ℕ)) →
                (∀ a ∈ B, ∀ b ∈ B, a ≤ B.card * a.gcd b) →
                  (∀ a ∈ B, ∀ (p k : ℕ), Nat.Prime p → p ^ k ∣ a → p ^ k < B.card) →
                    (B.card = 63 ∨ B.card = 105 ∨ B.card = 111 ∨ B.card = 153 ∨ B.card = 165 ∨ B.card = 679 ∨ B.card = 680) →
                      (∃ a ∈ B, ∃ b ∈ B, (↑(a.gcd b) : ℚ) ≤ (↑a : ℚ) / (↑B.card : ℚ)))
        ∧ (∀ (B : Finset ℕ),
      (0 : ℕ) ∉ B →
        B.Nonempty →
          B.gcd id = (1 : ℕ) →
            ¬Nat.Prime B.card →
              (∀ (q : ℕ), Nat.Prime q → B.card ≠ q + (1 : ℕ)) →
                (∀ a ∈ B, ∀ b ∈ B, a ≤ B.card * a.gcd b) →
                  (∀ a ∈ B, ∀ (p k : ℕ), Nat.Prime p → p ^ k ∣ a → p ^ k < B.card) →
                    200014 < B.card →
                      (∃ a ∈ B, ∃ b ∈ B, (↑(a.gcd b) : ℚ) ≤ (↑a : ℚ) / (↑B.card : ℚ)) ∨
                      ∃ (p : ℕ), Nat.Prime p ∧ B.card < p ∧ p < 2 * B.card ∧
                      (2 * B.card - p) * (2 * B.card - p) ≤ B.card)
        ∧ (∀ n : ℕ, 681 ≤ n → n ≤ 2228 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 2229 ≤ n → n ≤ 4844 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 4845 ≤ n → n ≤ 8527 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 8528 ≤ n → n ≤ 13392 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 13393 ≤ n → n ≤ 19388 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 19389 ≤ n → n ≤ 26540 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 26541 ≤ n → n ≤ 34904 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 34905 ≤ n → n ≤ 44504 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 44505 ≤ n → n ≤ 55208 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 55209 ≤ n → n ≤ 67128 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 67129 ≤ n → n ≤ 80268 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 80269 ≤ n → n ≤ 94617 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 94618 ≤ n → n ≤ 110089 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 110090 ≤ n → n ≤ 126814 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 126815 ≤ n → n ≤ 144754 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 144755 ≤ n → n ≤ 163941 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 163942 ≤ n → n ≤ 184361 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n)
        ∧ (∀ n : ℕ, 184362 ≤ n → n ≤ 200014 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n) := by
      refine ⟨?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
      · have hres : ∀ (B : Finset ℕ),
      (0 : ℕ) ∉ B →
        B.Nonempty →
          B.gcd id = (1 : ℕ) →
            ¬Nat.Prime B.card →
              (∀ (q : ℕ), Nat.Prime q → B.card ≠ q + (1 : ℕ)) →
                (∀ a ∈ B, ∀ b ∈ B, a ≤ B.card * a.gcd b) →
                  (∀ a ∈ B, ∀ (p k : ℕ), Nat.Prime p → p ^ k ∣ a → p ^ k < B.card) →
                    (B.card = 63 ∨ B.card = 105 ∨ B.card = 111 ∨ B.card = 153 ∨ B.card = 165 ∨ B.card = 679 ∨ B.card = 680) →
                      (∃ a ∈ B, ∃ b ∈ B, (↑(a.gcd b) : ℚ) ≤ (↑a : ℚ) / (↑B.card : ℚ)) := by
          sorry
        exact hres
      · have hlarge : ∀ (B : Finset ℕ),
      (0 : ℕ) ∉ B →
        B.Nonempty →
          B.gcd id = (1 : ℕ) →
            ¬Nat.Prime B.card →
              (∀ (q : ℕ), Nat.Prime q → B.card ≠ q + (1 : ℕ)) →
                (∀ a ∈ B, ∀ b ∈ B, a ≤ B.card * a.gcd b) →
                  (∀ a ∈ B, ∀ (p k : ℕ), Nat.Prime p → p ^ k ∣ a → p ^ k < B.card) →
                    200014 < B.card →
                      (∃ a ∈ B, ∃ b ∈ B, (↑(a.gcd b) : ℚ) ≤ (↑a : ℚ) / (↑B.card : ℚ)) ∨
                      ∃ (p : ℕ), Nat.Prime p ∧ B.card < p ∧ p < 2 * B.card ∧
                      (2 * B.card - p) * (2 * B.card - p) ≤ B.card := by
          sorry
        exact hlarge
      · have hw1 : ∀ n : ℕ, 681 ≤ n → n ≤ 2228 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw1
      · have hw2 : ∀ n : ℕ, 2229 ≤ n → n ≤ 4844 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw2
      · have hw3 : ∀ n : ℕ, 4845 ≤ n → n ≤ 8527 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw3
      · have hw4 : ∀ n : ℕ, 8528 ≤ n → n ≤ 13392 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw4
      · have hw5 : ∀ n : ℕ, 13393 ≤ n → n ≤ 19388 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw5
      · have hw6 : ∀ n : ℕ, 19389 ≤ n → n ≤ 26540 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw6
      · have hw7 : ∀ n : ℕ, 26541 ≤ n → n ≤ 34904 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw7
      · have hw8 : ∀ n : ℕ, 34905 ≤ n → n ≤ 44504 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw8
      · have hw9 : ∀ n : ℕ, 44505 ≤ n → n ≤ 55208 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw9
      · have hw10 : ∀ n : ℕ, 55209 ≤ n → n ≤ 67128 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw10
      · have hw11 : ∀ n : ℕ, 67129 ≤ n → n ≤ 80268 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw11
      · have hw12 : ∀ n : ℕ, 80269 ≤ n → n ≤ 94617 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw12
      · have hw13 : ∀ n : ℕ, 94618 ≤ n → n ≤ 110089 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw13
      · have hw14 : ∀ n : ℕ, 110090 ≤ n → n ≤ 126814 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw14
      · have hw15 : ∀ n : ℕ, 126815 ≤ n → n ≤ 144754 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw15
      · have hw16 : ∀ n : ℕ, 144755 ≤ n → n ≤ 163941 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw16
      · have hw17 : ∀ n : ℕ, 163942 ≤ n → n ≤ 184361 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw17
      · have hw18 : ∀ n : ℕ, 184362 ≤ n → n ≤ 200014 → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
          sorry
        exact hw18
    obtain ⟨hres, hlarge, hw1, hw2, hw3, hw4, hw5, hw6, hw7, hw8, hw9, hw10, hw11, hw12, hw13, hw14, hw15, hw16, hw17, hw18⟩ := hall
    have blk : ∀ (p lo hi k : ℕ), p.Prime → hi < p → p < 2 * lo → 2 * hi - p = k → k * k ≤ lo →
        ∀ n : ℕ, lo ≤ n → n ≤ hi → ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
      intro p lo hi k hp h1 h2 h3 h4 n hl hh
      refine ⟨p, hp, by omega, by omega, ?_⟩
      have : 2 * n - p ≤ k := by omega
      exact le_trans (Nat.mul_le_mul this this) (by omega)
    have hsmall : ∀ n : ℕ, 2 ≤ n → n ≤ 680 → n ≠ 5 → n ≠ 8 → n ≠ 14 → n ≠ 18 → n ≠ 48 → n ≠ 61 → n ≠ 62 → n ≠ 63 → n ≠ 74 → n ≠ 105 → n ≠ 111 → n ≠ 153 → n ≠ 165 → n ≠ 270 → n ≠ 677 → n ≠ 678 → n ≠ 679 → n ≠ 680 →
        ∃ p : ℕ, p.Prime ∧ n < p ∧ p < 2 * n ∧ (2 * n - p) * (2 * n - p) ≤ n := by
      intro n h2 h680 e5 e8 e14 e18 e48 e61 e62 e63 e74 e105 e111 e153 e165 e270 e677 e678 e679 e680
      by_cases c2 : n ≤ 2
      · exact blk 3 2 2 1 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c2
      by_cases c3 : n ≤ 3
      · exact blk 5 3 3 1 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c3
      by_cases c4 : n ≤ 4
      · exact blk 7 4 4 1 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c4
      by_cases c6 : n ≤ 6
      · exact blk 11 6 6 1 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c6
      by_cases c7 : n ≤ 7
      · exact blk 13 7 7 1 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c7
      by_cases c10 : n ≤ 10
      · exact blk 17 9 10 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c10
      by_cases c11 : n ≤ 11
      · exact blk 19 11 11 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c11
      by_cases c13 : n ≤ 13
      · exact blk 23 12 13 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c13
      by_cases c16 : n ≤ 16
      · exact blk 29 15 16 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c16
      by_cases c17 : n ≤ 17
      · exact blk 31 17 17 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c17
      by_cases c20 : n ≤ 20
      · exact blk 37 19 20 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c20
      by_cases c22 : n ≤ 22
      · exact blk 41 21 22 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c22
      by_cases c23 : n ≤ 23
      · exact blk 43 23 23 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c23
      by_cases c25 : n ≤ 25
      · exact blk 47 24 25 3 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c25
      by_cases c26 : n ≤ 26
      · exact blk 47 26 26 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c26
      by_cases c29 : n ≤ 29
      · exact blk 53 27 29 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c29
      by_cases c32 : n ≤ 32
      · exact blk 59 30 32 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c32
      by_cases c33 : n ≤ 33
      · exact blk 61 33 33 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c33
      by_cases c36 : n ≤ 36
      · exact blk 67 34 36 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c36
      by_cases c39 : n ≤ 39
      · exact blk 73 37 39 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c39
      by_cases c42 : n ≤ 42
      · exact blk 79 40 42 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c42
      by_cases c44 : n ≤ 44
      · exact blk 83 43 44 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c44
      by_cases c47 : n ≤ 47
      · exact blk 89 45 47 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c47
      by_cases c52 : n ≤ 52
      · exact blk 97 49 52 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c52
      by_cases c55 : n ≤ 55
      · exact blk 103 53 55 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c55
      by_cases c58 : n ≤ 58
      · exact blk 109 56 58 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c58
      by_cases c60 : n ≤ 60
      · exact blk 113 59 60 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c60
      by_cases c67 : n ≤ 67
      · exact blk 127 64 67 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c67
      by_cases c69 : n ≤ 69
      · exact blk 131 68 69 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c69
      by_cases c73 : n ≤ 73
      · exact blk 139 70 73 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c73
      by_cases c78 : n ≤ 78
      · exact blk 149 75 78 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c78
      by_cases c82 : n ≤ 82
      · exact blk 157 79 82 7 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c82
      by_cases c86 : n ≤ 86
      · exact blk 163 83 86 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c86
      by_cases c91 : n ≤ 91
      · exact blk 173 87 91 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c91
      by_cases c95 : n ≤ 95
      · exact blk 181 92 95 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c95
      by_cases c100 : n ≤ 100
      · exact blk 191 96 100 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c100
      by_cases c104 : n ≤ 104
      · exact blk 199 101 104 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c104
      by_cases c110 : n ≤ 110
      · exact blk 211 106 110 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c110
      by_cases c116 : n ≤ 116
      · exact blk 223 112 116 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c116
      by_cases c121 : n ≤ 121
      · exact blk 233 117 121 9 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c121
      by_cases c126 : n ≤ 126
      · exact blk 241 122 126 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c126
      by_cases c131 : n ≤ 131
      · exact blk 251 127 131 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c131
      by_cases c137 : n ≤ 137
      · exact blk 263 132 137 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c137
      by_cases c141 : n ≤ 141
      · exact blk 271 138 141 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c141
      by_cases c147 : n ≤ 147
      · exact blk 283 142 147 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c147
      by_cases c152 : n ≤ 152
      · exact blk 293 148 152 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c152
      by_cases c159 : n ≤ 159
      · exact blk 307 154 159 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c159
      by_cases c164 : n ≤ 164
      · exact blk 317 160 164 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c164
      by_cases c171 : n ≤ 171
      · exact blk 331 166 171 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c171
      by_cases c175 : n ≤ 175
      · exact blk 337 172 175 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c175
      by_cases c181 : n ≤ 181
      · exact blk 349 176 181 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c181
      by_cases c186 : n ≤ 186
      · exact blk 359 182 186 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c186
      by_cases c193 : n ≤ 193
      · exact blk 373 187 193 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c193
      by_cases c198 : n ≤ 198
      · exact blk 383 194 198 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c198
      by_cases c205 : n ≤ 205
      · exact blk 397 199 205 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c205
      by_cases c211 : n ≤ 211
      · exact blk 409 206 211 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c211
      by_cases c217 : n ≤ 217
      · exact blk 421 212 217 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c217
      by_cases c223 : n ≤ 223
      · exact blk 433 218 223 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c223
      by_cases c228 : n ≤ 228
      · exact blk 443 224 228 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c228
      by_cases c236 : n ≤ 236
      · exact blk 457 229 236 15 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c236
      by_cases c241 : n ≤ 241
      · exact blk 467 237 241 15 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c241
      by_cases c247 : n ≤ 247
      · exact blk 479 242 247 15 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c247
      by_cases c253 : n ≤ 253
      · exact blk 491 248 253 15 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c253
      by_cases c259 : n ≤ 259
      · exact blk 503 254 259 15 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c259
      by_cases c262 : n ≤ 262
      · exact blk 509 260 262 15 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c262
      by_cases c269 : n ≤ 269
      · exact blk 523 263 269 15 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c269
      by_cases c278 : n ≤ 278
      · exact blk 541 271 278 15 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c278
      by_cases c286 : n ≤ 286
      · exact blk 557 279 286 15 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c286
      by_cases c293 : n ≤ 293
      · exact blk 571 287 293 15 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c293
      by_cases c302 : n ≤ 302
      · exact blk 587 294 302 17 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c302
      by_cases c309 : n ≤ 309
      · exact blk 601 303 309 17 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c309
      by_cases c318 : n ≤ 318
      · exact blk 619 310 318 17 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c318
      by_cases c324 : n ≤ 324
      · exact blk 631 319 324 17 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c324
      by_cases c332 : n ≤ 332
      · exact blk 647 325 332 17 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c332
      by_cases c339 : n ≤ 339
      · exact blk 661 333 339 17 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c339
      by_cases c347 : n ≤ 347
      · exact blk 677 340 347 17 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c347
      by_cases c354 : n ≤ 354
      · exact blk 691 348 354 17 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c354
      by_cases c363 : n ≤ 363
      · exact blk 709 355 363 17 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c363
      by_cases c373 : n ≤ 373
      · exact blk 727 364 373 19 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c373
      by_cases c381 : n ≤ 381
      · exact blk 743 374 381 19 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c381
      by_cases c390 : n ≤ 390
      · exact blk 761 382 390 19 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c390
      by_cases c396 : n ≤ 396
      · exact blk 773 391 396 19 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c396
      by_cases c403 : n ≤ 403
      · exact blk 787 397 403 19 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c403
      by_cases c408 : n ≤ 408
      · exact blk 797 404 408 19 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c408
      by_cases c415 : n ≤ 415
      · exact blk 811 409 415 19 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c415
      by_cases c424 : n ≤ 424
      · exact blk 829 416 424 19 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c424
      by_cases c429 : n ≤ 429
      · exact blk 839 425 429 19 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c429
      by_cases c439 : n ≤ 439
      · exact blk 859 430 439 19 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c439
      by_cases c448 : n ≤ 448
      · exact blk 877 440 448 19 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c448
      by_cases c454 : n ≤ 454
      · exact blk 887 449 454 21 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c454
      by_cases c464 : n ≤ 464
      · exact blk 907 455 464 21 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c464
      by_cases c475 : n ≤ 475
      · exact blk 929 465 475 21 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c475
      by_cases c484 : n ≤ 484
      · exact blk 947 476 484 21 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c484
      by_cases c494 : n ≤ 494
      · exact blk 967 485 494 21 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c494
      by_cases c502 : n ≤ 502
      · exact blk 983 495 502 21 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c502
      by_cases c509 : n ≤ 509
      · exact blk 997 503 509 21 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c509
      by_cases c520 : n ≤ 520
      · exact blk 1019 510 520 21 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c520
      by_cases c530 : n ≤ 530
      · exact blk 1039 521 530 21 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c530
      by_cases c542 : n ≤ 542
      · exact blk 1061 531 542 23 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c542
      by_cases c546 : n ≤ 546
      · exact blk 1069 543 546 23 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c546
      by_cases c558 : n ≤ 558
      · exact blk 1093 547 558 23 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c558
      by_cases c570 : n ≤ 570
      · exact blk 1117 559 570 23 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c570
      by_cases c576 : n ≤ 576
      · exact blk 1129 571 576 23 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c576
      by_cases c588 : n ≤ 588
      · exact blk 1153 577 588 23 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c588
      by_cases c597 : n ≤ 597
      · exact blk 1171 589 597 23 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c597
      by_cases c608 : n ≤ 608
      · exact blk 1193 598 608 23 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c608
      by_cases c620 : n ≤ 620
      · exact blk 1217 609 620 23 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c620
      by_cases c630 : n ≤ 630
      · exact blk 1237 621 630 23 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c630
      by_cases c642 : n ≤ 642
      · exact blk 1259 631 642 25 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c642
      by_cases c654 : n ≤ 654
      · exact blk 1283 643 654 25 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c654
      by_cases c666 : n ≤ 666
      · exact blk 1307 655 666 25 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c666
      by_cases c676 : n ≤ 676
      · exact blk 1327 667 676 25 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num) n (by omega) c676
      omega
    intro B h0 hne hg hnp hq hle hpk
    have hpos : 0 < B.card := Finset.card_pos.mpr hne
    by_cases hbig : 200014 < B.card
    · exact hlarge B h0 hne hg hnp hq hle hpk hbig
    by_cases c184362 : 184362 ≤ B.card
    · exact Or.inr (hw18 B.card c184362 (by omega))
    by_cases c163942 : 163942 ≤ B.card
    · exact Or.inr (hw17 B.card c163942 (by omega))
    by_cases c144755 : 144755 ≤ B.card
    · exact Or.inr (hw16 B.card c144755 (by omega))
    by_cases c126815 : 126815 ≤ B.card
    · exact Or.inr (hw15 B.card c126815 (by omega))
    by_cases c110090 : 110090 ≤ B.card
    · exact Or.inr (hw14 B.card c110090 (by omega))
    by_cases c94618 : 94618 ≤ B.card
    · exact Or.inr (hw13 B.card c94618 (by omega))
    by_cases c80269 : 80269 ≤ B.card
    · exact Or.inr (hw12 B.card c80269 (by omega))
    by_cases c67129 : 67129 ≤ B.card
    · exact Or.inr (hw11 B.card c67129 (by omega))
    by_cases c55209 : 55209 ≤ B.card
    · exact Or.inr (hw10 B.card c55209 (by omega))
    by_cases c44505 : 44505 ≤ B.card
    · exact Or.inr (hw9 B.card c44505 (by omega))
    by_cases c34905 : 34905 ≤ B.card
    · exact Or.inr (hw8 B.card c34905 (by omega))
    by_cases c26541 : 26541 ≤ B.card
    · exact Or.inr (hw7 B.card c26541 (by omega))
    by_cases c19389 : 19389 ≤ B.card
    · exact Or.inr (hw6 B.card c19389 (by omega))
    by_cases c13393 : 13393 ≤ B.card
    · exact Or.inr (hw5 B.card c13393 (by omega))
    by_cases c8528 : 8528 ≤ B.card
    · exact Or.inr (hw4 B.card c8528 (by omega))
    by_cases c4845 : 4845 ≤ B.card
    · exact Or.inr (hw3 B.card c4845 (by omega))
    by_cases c2229 : 2229 ≤ B.card
    · exact Or.inr (hw2 B.card c2229 (by omega))
    by_cases c681 : 681 ≤ B.card
    · exact Or.inr (hw1 B.card c681 (by omega))
    by_cases h7 : B.card = 63 ∨ B.card = 105 ∨ B.card = 111 ∨ B.card = 153 ∨ B.card = 165 ∨ B.card = 679 ∨ B.card = 680
    · exact Or.inl (hres B h0 hne hg hnp hq hle hpk h7)
    by_cases h1 : B.card = 1
    · obtain ⟨a, ha⟩ := hne
      refine Or.inl ⟨a, ha, a, ha, ?_⟩
      rw [h1]
      simp
    have x5 : B.card ≠ 5 := by
      intro h
      rw [h] at hnp
      exact hnp (by norm_num)
    have x8 : B.card ≠ 8 := hq 7 (by norm_num)
    have x14 : B.card ≠ 14 := hq 13 (by norm_num)
    have x18 : B.card ≠ 18 := hq 17 (by norm_num)
    have x48 : B.card ≠ 48 := hq 47 (by norm_num)
    have x61 : B.card ≠ 61 := by
      intro h
      rw [h] at hnp
      exact hnp (by norm_num)
    have x62 : B.card ≠ 62 := hq 61 (by norm_num)
    have x74 : B.card ≠ 74 := hq 73 (by norm_num)
    have x270 : B.card ≠ 270 := hq 269 (by norm_num)
    have x677 : B.card ≠ 677 := by
      intro h
      rw [h] at hnp
      exact hnp (by norm_num)
    have x678 : B.card ≠ 678 := hq 677 (by norm_num)
    exact Or.inr (hsmall B.card (by omega) (by omega) x5 x8 x14 x18 x48 x61 x62 (by omega) x74 (by omega) (by omega) (by omega) (by omega) x270 x677 x678 (by omega) (by omega))
  obtain ⟨cls, hcls⟩ : ∃ cls : ℕ → ℕ → ℕ, ∀ p a, cls p a =
      min (ZMod.val ((a / p ^ a.factorization p : ℕ) : ZMod p))
        (p - ZMod.val ((a / p ^ a.factorization p : ℕ) : ZMod p)) := ⟨_, fun _ _ => rfl⟩

  -- 402-R4-c. Arithmetic heart of the rectangle lemma: two coprime divisors of α whose ratio is
  -- squeezed between α/n and n/α are equal (hence both 1), when α is within k of n and k² ≤ n.
  have r4c_arith (n k α e1 e2 : ℕ) (hk : k * k ≤ n) (hα : n < α + k)
      (he : e1 * e2 ≤ α) (h1 : α * e1 < n * e2) (h4 : α * e2 < n * e1) : e1 = e2 := by
    have key : ∀ x y : ℕ, x < y → x * y ≤ α → α * y < n * x → False := by
      intro x y hxy hx h
      have hαn : α ≤ n := by
        by_contra hc
        have : n * x ≤ α * y := Nat.mul_le_mul (by omega) (by omega)
        omega
      obtain ⟨s, rfl⟩ : ∃ s, n = α + s := ⟨n - α, by omega⟩
      have hs : s < k := by omega
      have a1 : α * (x + 1) ≤ α * y := Nat.mul_le_mul_left _ hxy
      have a2 : α < s * x := by nlinarith
      have a3 : x * (x + 1) ≤ x * y := Nat.mul_le_mul_left _ hxy
      have a4 : x + 1 < s := by
        by_contra hc
        have : s * x ≤ (x + 1) * x := Nat.mul_le_mul_right _ (by omega)
        nlinarith
      have a5 : (s + 1) * (s + 1) ≤ k * k := Nat.mul_le_mul hs hs
      have a6 : s * x ≤ s * s := Nat.mul_le_mul_left _ (by omega)
      nlinarith
    rcases Nat.lt_trichotomy e1 e2 with h | h | h
    · exact (key e1 e2 h he h4).elim
    · exact h
    · exact (key e2 e1 h (by rwa [Nat.mul_comm]) h1).elim


  -- 402-R4-c. Rectangle lemma, coprime core: α, β coprime and both within k of n (k² ≤ n), d1, d2
  -- coprime; if all four cross quotients of {α d1, β d1, α d2, β d2} are below n then d1 = d2 = 1.
  have r4c_rect_core (n k α β d1 d2 : ℕ) (hk : k * k ≤ n) (hα : n < α + k) (hβ : n < β + k)
      (α0 : 0 < α) (β0 : 0 < β) (hαβ : Nat.Coprime α β) (hd : Nat.Coprime d1 d2)
      (h1 : 0 < d1) (h2 : 0 < d2)
      (H1 : α * d1 < n * Nat.gcd (α * d1) (β * d2)) (H2 : β * d2 < n * Nat.gcd (α * d1) (β * d2))
      (H3 : β * d1 < n * Nat.gcd (β * d1) (α * d2)) (H4 : α * d2 < n * Nat.gcd (β * d1) (α * d2)) :
      d1 = 1 ∧ d2 = 1 := by
    have e1p : 0 < Nat.gcd α d1 := Nat.gcd_pos_of_pos_left _ α0
    have e2p : 0 < Nat.gcd α d2 := Nat.gcd_pos_of_pos_left _ α0
    have f1p : 0 < Nat.gcd β d1 := Nat.gcd_pos_of_pos_left _ β0
    have f2p : 0 < Nat.gcd β d2 := Nat.gcd_pos_of_pos_left _ β0
    have hG : Nat.gcd (α * d1) (β * d2) ≤ Nat.gcd α d2 * Nat.gcd β d1 := by
      apply Nat.le_of_dvd (Nat.mul_pos e2p f1p)
      have h := Nat.gcd_mul_right_dvd_mul_gcd (α * d1) β d2
      rw [Nat.Coprime.gcd_mul_left_cancel d1 hαβ, Nat.Coprime.gcd_mul_right_cancel α hd] at h
      rw [Nat.gcd_comm d1 β, Nat.mul_comm (β.gcd d1)] at h; exact h
    have hG' : Nat.gcd (β * d1) (α * d2) ≤ Nat.gcd α d1 * Nat.gcd β d2 := by
      apply Nat.le_of_dvd (Nat.mul_pos e1p f2p)
      have h := Nat.gcd_mul_right_dvd_mul_gcd (β * d1) α d2
      rw [Nat.Coprime.gcd_mul_left_cancel d1 hαβ.symm, Nat.Coprime.gcd_mul_right_cancel β hd] at h
      rw [Nat.gcd_comm d1 α] at h; exact h
    have ce : Nat.Coprime (Nat.gcd α d1) (Nat.gcd α d2) :=
      Nat.Coprime.coprime_dvd_left (Nat.gcd_dvd_right _ _)
        (Nat.Coprime.coprime_dvd_right (Nat.gcd_dvd_right _ _) hd)
    have cf : Nat.Coprime (Nat.gcd β d1) (Nat.gcd β d2) :=
      Nat.Coprime.coprime_dvd_left (Nat.gcd_dvd_right _ _)
        (Nat.Coprime.coprime_dvd_right (Nat.gcd_dvd_right _ _) hd)
    have c1 : Nat.Coprime (Nat.gcd α d1) (Nat.gcd β d1) :=
      Nat.Coprime.coprime_dvd_left (Nat.gcd_dvd_left _ _)
        (Nat.Coprime.coprime_dvd_right (Nat.gcd_dvd_left _ _) hαβ)
    have c2 : Nat.Coprime (Nat.gcd α d2) (Nat.gcd β d2) :=
      Nat.Coprime.coprime_dvd_left (Nat.gcd_dvd_left _ _)
        (Nat.Coprime.coprime_dvd_right (Nat.gcd_dvd_left _ _) hαβ)
    have m1 : Nat.gcd α d1 * Nat.gcd β d1 ≤ d1 := Nat.le_of_dvd h1
      (Nat.Coprime.mul_dvd_of_dvd_of_dvd c1 (Nat.gcd_dvd_right _ _) (Nat.gcd_dvd_right _ _))
    have m2 : Nat.gcd α d2 * Nat.gcd β d2 ≤ d2 := Nat.le_of_dvd h2
      (Nat.Coprime.mul_dvd_of_dvd_of_dvd c2 (Nat.gcd_dvd_right _ _) (Nat.gcd_dvd_right _ _))
    have mα : Nat.gcd α d1 * Nat.gcd α d2 ≤ α := Nat.le_of_dvd α0
      (Nat.Coprime.mul_dvd_of_dvd_of_dvd ce (Nat.gcd_dvd_left _ _) (Nat.gcd_dvd_left _ _))
    have mβ : Nat.gcd β d1 * Nat.gcd β d2 ≤ β := Nat.le_of_dvd β0
      (Nat.Coprime.mul_dvd_of_dvd_of_dvd cf (Nat.gcd_dvd_left _ _) (Nat.gcd_dvd_left _ _))
    generalize Nat.gcd α d1 = e1 at *
    generalize Nat.gcd α d2 = e2 at *
    generalize Nat.gcd β d1 = f1 at *
    generalize Nat.gcd β d2 = f2 at *
    generalize Nat.gcd (α * d1) (β * d2) = G at *
    generalize Nat.gcd (β * d1) (α * d2) = G' at *
    have i1 : α * e1 < n * e2 := by
      have a : α * (e1 * f1) ≤ α * d1 := Nat.mul_le_mul_left _ m1
      have b : n * G ≤ n * (e2 * f1) := Nat.mul_le_mul_left _ hG
      have c : (α * e1) * f1 < (n * e2) * f1 := by
        calc (α * e1) * f1 = α * (e1 * f1) := by ring
          _ ≤ α * d1 := a
          _ < n * G := H1
          _ ≤ n * (e2 * f1) := b
          _ = (n * e2) * f1 := by ring
      exact Nat.lt_of_mul_lt_mul_right c
    have i4 : α * e2 < n * e1 := by
      have a : α * (e2 * f2) ≤ α * d2 := Nat.mul_le_mul_left _ m2
      have b : n * G' ≤ n * (e1 * f2) := Nat.mul_le_mul_left _ hG'
      have c : (α * e2) * f2 < (n * e1) * f2 := by
        calc (α * e2) * f2 = α * (e2 * f2) := by ring
          _ ≤ α * d2 := a
          _ < n * G' := H4
          _ ≤ n * (e1 * f2) := b
          _ = (n * e1) * f2 := by ring
      exact Nat.lt_of_mul_lt_mul_right c
    have i2 : β * f2 < n * f1 := by
      have a : β * (e2 * f2) ≤ β * d2 := Nat.mul_le_mul_left _ m2
      have b : n * G ≤ n * (e2 * f1) := Nat.mul_le_mul_left _ hG
      have c : (β * f2) * e2 < (n * f1) * e2 := by
        calc (β * f2) * e2 = β * (e2 * f2) := by ring
          _ ≤ β * d2 := a
          _ < n * G := H2
          _ ≤ n * (e2 * f1) := b
          _ = (n * f1) * e2 := by ring
      exact Nat.lt_of_mul_lt_mul_right c
    have i3 : β * f1 < n * f2 := by
      have a : β * (e1 * f1) ≤ β * d1 := Nat.mul_le_mul_left _ m1
      have b : n * G' ≤ n * (e1 * f2) := Nat.mul_le_mul_left _ hG'
      have c : (β * f1) * e1 < (n * f2) * e1 := by
        calc (β * f1) * e1 = β * (e1 * f1) := by ring
          _ ≤ β * d1 := a
          _ < n * G' := H3
          _ ≤ n * (e1 * f2) := b
          _ = (n * f2) * e1 := by ring
      exact Nat.lt_of_mul_lt_mul_right c
    have ee : e1 = e2 := r4c_arith n k α e1 e2 hk hα mα i1 i4
    have ff : f1 = f2 := r4c_arith n k β f1 f2 hk hβ mβ i3 i2
    subst ee; subst ff
    have e1 : e1 = 1 := Nat.coprime_self e1 |>.mp ce
    have f1 : f1 = 1 := Nat.coprime_self f1 |>.mp cf
    subst e1; subst f1
    have kα : k ≤ α := by
      by_contra hc
      have : (α + 1) * k ≤ k * k := Nat.mul_le_mul_right _ (by omega)
      nlinarith
    have g1 : n * G ≤ n := by simpa using Nat.mul_le_mul_left n hG
    have g2 : n * G' ≤ n := by simpa using Nat.mul_le_mul_left n hG'
    constructor
    · by_contra hc
      have : α * 2 ≤ α * d1 := Nat.mul_le_mul_left _ (by omega)
      omega
    · by_contra hc
      have : α * 2 ≤ α * d2 := Nat.mul_le_mul_left _ (by omega)
      omega


  -- 402-R4-c. Collision lemma for one pair: both quotients below n ≤ p and equal fold classes
  -- force a = b or reduced quotients adding up to p.
  have r4c_pair (p n a b : ℕ) (hp : p.Prime) (hnp : n ≤ p) (a0 : 0 < a) (b0 : 0 < b)
      (ha : a < n * Nat.gcd a b) (hb : b < n * Nat.gcd a b) (hc : cls p a = cls p b) :
      a = b ∨ ∃ x y g, x + y = p ∧ Nat.Coprime x y ∧ a = x * g ∧ b = y * g := by
    have := Fact.mk hp
    obtain ⟨x, y, hxy, hax, hby⟩ := Nat.exists_coprime a b
    have g0 : 0 < Nat.gcd a b := Nat.gcd_pos_of_pos_left _ a0
    generalize Nat.gcd a b = g at *
    have xn : x < n := by
      rw [hax] at ha; exact Nat.lt_of_mul_lt_mul_right ha
    have yn : y < n := by
      rw [hby] at hb; exact Nat.lt_of_mul_lt_mul_right hb
    have x0 : 0 < x := by
      rcases Nat.eq_zero_or_pos x with h | h
      · subst h; omega
      · exact h
    have y0 : 0 < y := by
      rcases Nat.eq_zero_or_pos y with h | h
      · subst h; omega
      · exact h
    have key : a * y = b * x := by rw [hax, hby]; ring
    have oc : ∀ z : ℕ, 0 < z → z < p → z / p ^ z.factorization p = z := by
      intro z hz hzp
      have : ¬ p ∣ z := fun h => by have := Nat.le_of_dvd hz h; omega
      rw [Nat.factorization_eq_zero_of_not_dvd this]; simp
    have key2 : (a / p ^ a.factorization p) * y = (b / p ^ b.factorization p) * x := by
      have h := congrArg (fun m => m / p ^ m.factorization p) key
      simp only [Nat.ordCompl_mul] at h
      rwa [oc y y0 (by omega), oc x x0 (by omega)] at h
    have na : ((a / p ^ a.factorization p : ℕ) : ZMod p) ≠ 0 := by
      rw [Ne, ZMod.natCast_eq_zero_iff]; exact Nat.not_dvd_ordCompl hp (by omega)
    have nb : ((b / p ^ b.factorization p : ℕ) : ZMod p) ≠ 0 := by
      rw [Ne, ZMod.natCast_eq_zero_iff]; exact Nat.not_dvd_ordCompl hp (by omega)
    have key3 : ((a / p ^ a.factorization p : ℕ) : ZMod p) * (y : ZMod p)
        = ((b / p ^ b.factorization p : ℕ) : ZMod p) * (x : ZMod p) := by
      exact_mod_cast congrArg (Nat.cast : ℕ → ZMod p) key2
    rw [hcls, hcls] at hc
    generalize ((a / p ^ a.factorization p : ℕ) : ZMod p) = ra at *
    generalize ((b / p ^ b.factorization p : ℕ) : ZMod p) = rb at *
    have va := ZMod.val_lt ra
    have vb := ZMod.val_lt rb
    have va0 : 0 < ra.val := (ZMod.val_pos).mpr na
    have vb0 : 0 < rb.val := (ZMod.val_pos).mpr nb
    have hcase : ra.val = rb.val ∨ ra.val + rb.val = p := by omega
    rcases hcase with h | h
    · left
      have hr : ra = rb := ZMod.val_injective p h
      rw [hr] at key3
      have h2 : (y : ZMod p) = (x : ZMod p) := mul_left_cancel₀ nb key3
      have h3 := (ZMod.natCast_eq_natCast_iff' y x p).mp h2
      rw [Nat.mod_eq_of_lt (by omega), Nat.mod_eq_of_lt (by omega)] at h3
      rw [hax, hby, h3]
    · right
      have hr : ra + rb = 0 := by
        have h4 : ((ra.val + rb.val : ℕ) : ZMod p) = ((p : ℕ) : ZMod p) := by rw [h]
        rw [Nat.cast_add, ZMod.natCast_zmod_val, ZMod.natCast_zmod_val, ZMod.natCast_self] at h4
        exact h4
      have hra : ra = -rb := eq_neg_of_add_eq_zero_left hr
      rw [hra] at key3
      have h5 : rb * ((x : ZMod p) + (y : ZMod p)) = 0 := by
        have : rb * ((x : ZMod p) + (y : ZMod p)) = rb * x - (-rb * y) := by ring
        rw [this, key3]; ring
      have h6 : ((x + y : ℕ) : ZMod p) = 0 := by
        rcases mul_eq_zero.mp h5 with h | h
        · exact (nb h).elim
        · exact_mod_cast h
      rw [ZMod.natCast_eq_zero_iff] at h6
      exact ⟨x, y, g, Nat.eq_of_dvd_of_lt_two_mul (by omega) h6 (by omega), hxy, hax, hby⟩


  -- 402-R4-c. Rectangle lemma: α u, β u, α w, β w with all four cross quotients below n force u = w.
  have r4c_rect (n k α β u w : ℕ) (hk : k * k ≤ n) (hα : n < α + k) (hβ : n < β + k)
      (α0 : 0 < α) (β0 : 0 < β) (hαβ : Nat.Coprime α β) (u0 : 0 < u) (w0 : 0 < w)
      (H1 : α * u < n * Nat.gcd (α * u) (β * w)) (H2 : β * w < n * Nat.gcd (α * u) (β * w))
      (H3 : β * u < n * Nat.gcd (β * u) (α * w)) (H4 : α * w < n * Nat.gcd (β * u) (α * w)) :
      u = w := by
    obtain ⟨d1, d2, hd, hu, hw⟩ := Nat.exists_coprime u w
    have C0 : 0 < Nat.gcd u w := Nat.gcd_pos_of_pos_left _ u0
    generalize Nat.gcd u w = C at *
    subst hu; subst hw
    have d10 : 0 < d1 := Nat.pos_of_mul_pos_right u0
    have d20 : 0 < d2 := Nat.pos_of_mul_pos_right w0
    have s1 : Nat.gcd (α * (d1 * C)) (β * (d2 * C)) = Nat.gcd (α * d1) (β * d2) * C := by
      rw [← Nat.mul_assoc, ← Nat.mul_assoc, Nat.gcd_mul_right]
    have s2 : Nat.gcd (β * (d1 * C)) (α * (d2 * C)) = Nat.gcd (β * d1) (α * d2) * C := by
      rw [← Nat.mul_assoc, ← Nat.mul_assoc, Nat.gcd_mul_right]
    rw [s1] at H1 H2
    rw [s2] at H3 H4
    have c : ∀ s t : ℕ, s * (t * C) < n * (Nat.gcd (α * d1) (β * d2) * C) →
        s * t < n * Nat.gcd (α * d1) (β * d2) := by
      intro s t h
      rw [← Nat.mul_assoc, ← Nat.mul_assoc] at h; exact Nat.lt_of_mul_lt_mul_right h
    have c' : ∀ s t : ℕ, s * (t * C) < n * (Nat.gcd (β * d1) (α * d2) * C) →
        s * t < n * Nat.gcd (β * d1) (α * d2) := by
      intro s t h
      rw [← Nat.mul_assoc, ← Nat.mul_assoc] at h; exact Nat.lt_of_mul_lt_mul_right h
    obtain ⟨e1, e2⟩ := r4c_rect_core n k α β d1 d2 hk hα hβ α0 β0 hαβ hd d10 d20
      (c _ _ H1) (c _ _ H2) (c' _ _ H3) (c' _ _ H4)
    rw [e1, e2]

  -- 402-R4-c. THE CRITERION (Zaharescu's Proposition 1 in strict form): a prime p with
  -- n < p < 2n and (2n − p)² ≤ n forces a pair with n · gcd(a, b) ≤ a in every set of n positive integers.
  have r4c_criterion (A : Finset ℕ) (h0 : 0 ∉ A) (p : ℕ) (hp : p.Prime) (h1 : A.card < p)
      (h2 : p < 2 * A.card) (h3 : (2 * A.card - p) * (2 * A.card - p) ≤ A.card) :
      ∃ a ∈ A, ∃ b ∈ A, A.card * Nat.gcd a b ≤ a := by
    by_contra hne
    push Not at hne
    generalize hn : A.card = n at *
    have pos : ∀ a ∈ A, 0 < a := fun a ha =>
      Nat.pos_of_ne_zero (fun h => h0 (h ▸ ha))
    have podd : p % 2 = 1 := by
      rcases hp.eq_two_or_odd with h | h
      · omega
      · exact h
    -- pairs in one fold class
    have P : ∀ a ∈ A, ∀ b ∈ A, cls p a = cls p b →
        a = b ∨ ∃ x y g, x + y = p ∧ Nat.Coprime x y ∧ a = x * g ∧ b = y * g :=
      fun a ha b hb h => r4c_pair p n a b hp h1.le (pos a ha) (pos b hb) (hne a ha b hb)
        (by rw [Nat.gcd_comm]; exact hne b hb a ha) h
    have clsr : ∀ a ∈ A, cls p a ∈ Finset.Icc 1 ((p - 1) / 2) := by
      intro a ha
      have := Fact.mk hp
      have na : ((a / p ^ a.factorization p : ℕ) : ZMod p) ≠ 0 := by
        rw [Ne, ZMod.natCast_eq_zero_iff]; exact Nat.not_dvd_ordCompl hp (pos a ha).ne'
      have v1 := ZMod.val_lt ((a / p ^ a.factorization p : ℕ) : ZMod p)
      have v0 : 0 < ZMod.val ((a / p ^ a.factorization p : ℕ) : ZMod p) := (ZMod.val_pos).mpr na
      rw [hcls]
      rw [Finset.mem_Icc]
      omega
    classical
    -- the elements with a smaller partner in their class, and the rest
    have split := Finset.card_filter_add_card_filter_not (s := A)
      (fun a => ∃ a' ∈ A, a' < a ∧ cls p a' = cls p a)
    have c1 : (A.filter (fun a => ¬ ∃ a' ∈ A, a' < a ∧ cls p a' = cls p a)).card
        ≤ (Finset.Icc 1 ((p - 1) / 2)).card := by
      apply Finset.card_le_card_of_injOn (cls p)
      · intro a ha
        exact clsr a (Finset.mem_filter.mp (Finset.mem_coe.mp ha)).1
      · intro a ha b hb hab
        have ha' := Finset.mem_filter.mp (Finset.mem_coe.mp ha)
        have hb' := Finset.mem_filter.mp (Finset.mem_coe.mp hb)
        rcases Nat.lt_trichotomy a b with h | h | h
        · exact (hb'.2 ⟨a, ha'.1, h, hab⟩).elim
        · exact h
        · exact (ha'.2 ⟨b, hb'.1, h, hab.symm⟩).elim
    have hex : ∀ a, ∃ a' x y g, (∃ a' ∈ A, a' < a ∧ cls p a' = cls p a) → a ∈ A →
        (a' ∈ A ∧ a' < a ∧ x + y = p ∧ Nat.Coprime x y ∧ a = x * g ∧ a' = y * g) := by
      intro a
      by_cases h : (∃ a' ∈ A, a' < a ∧ cls p a' = cls p a) ∧ a ∈ A
      · obtain ⟨⟨a', ha', hlt, hc⟩, ha⟩ := h
        rcases P a ha a' ha' hc.symm with h | ⟨x, y, g, h⟩
        · omega
        · exact ⟨a', x, y, g, fun _ _ => ⟨ha', hlt, h⟩⟩
      · exact ⟨0, 0, 0, 0, fun h1 h2 => (h ⟨h1, h2⟩).elim⟩
    choose f X Y G hf using hex
    -- the rectangle step, with the four elements named
    have R : ∀ a a' b b' α β u w : ℕ, a ∈ A → a' ∈ A → b ∈ A → b' ∈ A → α + β = p →
        Nat.Coprime α β → a = α * u → a' = β * u → b = α * w → b' = β * w → u = w := by
      intro a a' b b' α β u w ha ha' hb hb' hs hco e1 e2 e3 e4
      have q1 := hne a ha b' hb'
      have q2 := hne b' hb' a ha
      have q3 := hne a' ha' b hb
      have q4 := hne b hb a' ha'
      rw [Nat.gcd_comm] at q2 q4
      have pa := pos a ha
      have pa' := pos a' ha'
      have pb := pos b hb
      have qa := hne a ha a' ha'
      have qa' := hne a' ha' a ha
      rw [Nat.gcd_comm] at qa'
      subst e1 e2 e3 e4
      have u0 : 0 < u := Nat.pos_of_mul_pos_left pa
      have w0 : 0 < w := Nat.pos_of_mul_pos_left pb
      have α0 : 0 < α := Nat.pos_of_mul_pos_right pa
      have β0 : 0 < β := Nat.pos_of_mul_pos_right pa'
      have gu : Nat.gcd (α * u) (β * u) = u := by
        rw [Nat.gcd_mul_right, hco, Nat.one_mul]
      rw [gu] at qa qa'
      have αn : α < n := Nat.lt_of_mul_lt_mul_right qa
      have βn : β < n := Nat.lt_of_mul_lt_mul_right qa'
      exact r4c_rect n (2 * n - p) α β u w h3 (by omega) (by omega) α0 β0 hco u0 w0 q1 q2 q3 q4
    have c2 : (A.filter (fun a => ∃ a' ∈ A, a' < a ∧ cls p a' = cls p a)).card
        ≤ (Finset.Icc ((p + 1) / 2) (n - 1)).card := by
      apply Finset.card_le_card_of_injOn (fun a => max (X a) (Y a))
      · intro a ha
        have ha' := Finset.mem_filter.mp (Finset.mem_coe.mp ha)
        obtain ⟨m1, m2, m3, m4, m5, m6⟩ := hf a ha'.2 ha'.1
        have qa := hne a ha'.1 (f a) m1
        have qa' := hne (f a) m1 a ha'.1
        rw [Nat.gcd_comm] at qa'
        have g0 : 0 < G a := Nat.pos_of_mul_pos_left (m5 ▸ pos a ha'.1)
        have gg : ∀ s t x y g : ℕ, s = x * g → t = y * g → Nat.Coprime x y → Nat.gcd s t = g := by
          intro s t x y g e1 e2 hc
          rw [e1, e2, Nat.gcd_mul_right, hc, Nat.one_mul]
        rw [gg a (f a) (X a) (Y a) (G a) m5 m6 m4] at qa qa'
        have xn : X a < n := by
          have : X a * G a < n * G a := lt_of_eq_of_lt m5.symm qa
          exact Nat.lt_of_mul_lt_mul_right this
        have yn : Y a < n := by
          have : Y a * G a < n * G a := lt_of_eq_of_lt m6.symm qa'
          exact Nat.lt_of_mul_lt_mul_right this
        simp only [Finset.coe_Icc, Set.mem_Icc]
        omega
      · intro a ha b hb hab
        have ha' := Finset.mem_filter.mp (Finset.mem_coe.mp ha)
        have hb' := Finset.mem_filter.mp (Finset.mem_coe.mp hb)
        obtain ⟨m1, m2, m3, m4, m5, m6⟩ := hf a ha'.2 ha'.1
        obtain ⟨k1, k2, k3, k4, k5, k6⟩ := hf b hb'.2 hb'.1
        simp only at hab
        have hcase : (X b = X a ∧ Y b = Y a) ∨ (X b = Y a ∧ Y b = X a) := by omega
        rcases hcase with ⟨hx, hy⟩ | ⟨hx, hy⟩
        · rw [hx] at k5; rw [hy] at k6
          have := R a (f a) b (f b) (X a) (Y a) (G a) (G b) ha'.1 m1 hb'.1 k1 m3 m4 m5 m6 k5 k6
          rw [m5, k5, this]
        · rw [hx] at k5; rw [hy] at k6
          have := R a (f a) (f b) b (X a) (Y a) (G a) (G b) ha'.1 m1 k1 hb'.1 m3 m4 m5 m6 k6 k5
          have e1 : a = f b := by rw [m5, k6, this]
          have e2 : f a = b := by rw [m6, k5, this]
          omega
    rw [Nat.card_Icc] at c1 c2
    omega
  intro B h0 hne hg hnp hq hle hpk
  left
  rcases hwin B h0 hne hg hnp hq hle hpk with h | ⟨p, hp, h1, h2, h3⟩
  · exact h
  · obtain ⟨a, ha, b, hb, h⟩ := r4c_criterion B h0 p hp h1 h2 h3
    refine ⟨a, ha, b, hb, ?_⟩
    have n0 : (0 : ℚ) < (B.card : ℚ) := by
      have : 0 < B.card := Finset.card_pos.mpr ⟨a, ha⟩
      exact_mod_cast this
    rw [le_div_iff₀ n0]
    have : a.gcd b * B.card ≤ a := by rw [Nat.mul_comm]; exact h
    exact_mod_cast this
