"""F03-T16 (audit 2026-10-04): the service serves ``frontier/v4`` and still serves ``frontier/v3``.

The live graph's products stay on the version its pinned gate renders until the re-pin, so the
service accepts the old version and the new one side by side (D-34: a consumer parses by version).
Both fixtures are golden copies from the gate (F05-Q5): ``frontier-listed.json`` regenerated by
``test_fixture_is_golden.write_fixtures`` at v4, and ``frontier-listed-v3.json`` the same recipe's
output at v3, kept byte for byte from before the bump.
"""

from __future__ import annotations

from pathlib import Path

from api_fakes import Harness
from mcp_client import McpClient

from opn_gate import schemas

FIXTURES = Path(__file__).resolve().parent / "fixtures"
LISTED_NODE = "listed-lemma"


def serve(harness: Harness, name: str) -> None:
    harness.githost.files["frontier.json"] = (FIXTURES / name).read_bytes()
    harness.githost.files["targets/index.json"] = (
        FIXTURES / "targets-index-listed.json"
    ).read_bytes()
    harness.context.files.clear()


def test_a_v3_frontier_is_still_served(harness: Harness) -> None:
    serve(harness, "frontier-listed-v3.json")
    r = harness.client.get("/frontier.json")
    assert r.status_code == 200, r.text
    doc = r.json()
    assert doc["schema"] == "frontier/v3"
    assert schemas.violations(doc) == []
    assert all("needs" not in e for e in doc["entries"])


def test_a_v4_frontier_is_served_with_what_each_node_needs(harness: Harness) -> None:
    serve(harness, "frontier-listed.json")
    r = harness.client.get("/frontier.json")
    assert r.status_code == 200, r.text
    doc = r.json()
    assert doc["schema"] == "frontier/v4"
    assert schemas.violations(doc) == []
    entry = next(e for e in doc["entries"] if e["node_id"] == LISTED_NODE)
    assert (entry["status"], entry["cause"], entry["needs"], entry["claimable"]) == (
        "ready",
        None,
        "proof",
        True,
    )


def test_list_frontier_filters_on_needs(harness: Harness) -> None:
    """The MCP filter set is drawn from the newest version, so ``needs`` is a field an agent can
    ask for; on a v3 document the same filter matches nothing rather than erroring (F11-R4)."""
    serve(harness, "frontier-listed.json")
    client = McpClient(harness)
    got = client.ok("list_frontier", {"filters": {"needs": "proof", "target_id": "listed-target"}})
    assert [e["node_id"] for e in got["entries"]] == [LISTED_NODE]
    assert client.ok("list_frontier", {"filters": {"needs": "witness"}})["entries"] == []
    serve(harness, "frontier-listed-v3.json")
    assert client.ok("list_frontier", {"filters": {"needs": "proof"}})["entries"] == []
