import Mathlib
import Nodes.«erdos-402--h3-v2--h1».Context

open Filter

/-! Hole `hcomp` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_402__h3_v2__h1 : ∀ (B : Finset ℕ),
  (0 : ℕ) ∉ B →
    B.Nonempty →
      B.gcd id = (1 : ℕ) →
        ¬Nat.Prime B.card →
          (∀ (q : ℕ), Nat.Prime q → B.card ≠ q + (1 : ℕ)) →
            (∀ a ∈ B, ∀ b ∈ B, a ≤ B.card * a.gcd b) →
              (∀ a ∈ B, ∀ (p k : ℕ), Nat.Prime p → p ^ k ∣ a → p ^ k < B.card) →
                ∃ a ∈ B, ∃ b ∈ B, (↑(a.gcd b) : ℚ) ≤ (↑a : ℚ) / (↑B.card : ℚ) := by
  have hsmooth : ∀ B : Finset ℕ, 0 ∉ B → B.Nonempty → B.gcd id = 1 → ¬ B.card.Prime →
      (∀ q : ℕ, q.Prime → B.card ≠ q + 1) →
      (∀ a ∈ B, ∀ b ∈ B, a < B.card * a.gcd b) →
      (∀ a ∈ B, ∀ p k : ℕ, p.Prime → p ^ k ∣ a → p ^ k < B.card) →
      (∀ p : ℕ, p.Prime → B.card ≤ 2 * p → ∀ a ∈ B, ¬ p ∣ a) → False := sorry
  have hlarge : ∀ B : Finset ℕ, 0 ∉ B → B.Nonempty → B.gcd id = 1 → ¬ B.card.Prime →
      (∀ q : ℕ, q.Prime → B.card ≠ q + 1) →
      (∀ a ∈ B, ∀ b ∈ B, a < B.card * a.gcd b) →
      (∀ a ∈ B, ∀ p k : ℕ, p.Prime → p ^ k ∣ a → p ^ k < B.card) →
      ∀ p : ℕ, p.Prime → B.card ≤ 2 * p → p < B.card →
      (∀ a ∈ B, p ∣ a → ∀ b ∈ B, ¬ p ∣ b → a = p * a.gcd b) →
      (∃ a ∈ B, p ∣ a) → (∃ b ∈ B, ¬ p ∣ b) → False := sorry
  intro B h0 hne hgcd hnp hnp1 hle hpp
  by_contra hcon
  have hn : 0 < B.card := hne.card_pos
  have hnq : (0 : ℚ) < B.card := by exact_mod_cast hn
  have hlt : ∀ a ∈ B, ∀ b ∈ B, a < B.card * a.gcd b := by
    intro a ha b hb
    rcases (hle a ha b hb).lt_or_eq with h | h
    · exact h
    · exfalso
      apply hcon
      refine ⟨a, ha, b, hb, ?_⟩
      rw [le_div_iff₀ hnq]
      have h2 : a.gcd b * B.card ≤ a := by rw [h, Nat.mul_comm]
      exact_mod_cast h2
  have hA : ∀ p : ℕ, p.Prime → B.card ≤ 2 * p →
      ∀ a ∈ B, p ∣ a → ∀ b ∈ B, ¬ p ∣ b → a = p * a.gcd b := by
    intro p hp hnp2 a ha hpa b hb hpb
    have ha0 : a ≠ 0 := fun h => h0 (h ▸ ha)
    have hg0 : 0 < a.gcd b := Nat.gcd_pos_of_pos_left b (Nat.pos_of_ne_zero ha0)
    obtain ⟨x, hx⟩ := Nat.gcd_dvd_left a b
    have hpg : ¬ p ∣ a.gcd b := fun h => hpb (h.trans (Nat.gcd_dvd_right a b))
    have hpx : p ∣ x := by
      have h1 : p ∣ a.gcd b * x := hx ▸ hpa
      exact (hp.dvd_mul.mp h1).resolve_left hpg
    obtain ⟨t, ht⟩ := hpx
    have hlt' := hlt a ha b hb
    have hxn : x < B.card := by
      have h3 : a.gcd b * x < a.gcd b * B.card := by
        rw [← hx, Nat.mul_comm]; exact hlt'
      exact Nat.lt_of_mul_lt_mul_left h3
    have ht1 : t = 1 := by
      have hx0 : x ≠ 0 := by
        rintro rfl
        rw [Nat.mul_zero] at hx
        exact ha0 hx
      have ht0 : t ≠ 0 := by
        rintro rfl
        rw [Nat.mul_zero] at ht
        exact hx0 ht
      by_contra hne1
      have ht2 : 2 ≤ t := by omega
      have h4 : p * 2 ≤ p * t := Nat.mul_le_mul_left p ht2
      omega
    rw [hx, ht, ht1, Nat.mul_one, Nat.mul_comm]
  by_cases hex : ∃ p : ℕ, p.Prime ∧ B.card ≤ 2 * p ∧ ∃ a ∈ B, p ∣ a
  · obtain ⟨p, hp, hnp2, a, ha, hpa⟩ := hex
    have hpn : p < B.card := by
      have h1 := hpp a ha p 1 hp (by rwa [pow_one])
      rwa [pow_one] at h1
    have hexb : ∃ b ∈ B, ¬ p ∣ b := by
      by_contra h
      push Not at h
      have h1 : p ∣ B.gcd id := Finset.dvd_gcd (fun b hb => h b hb)
      rw [hgcd] at h1
      exact hp.one_lt.ne' (Nat.dvd_one.mp h1)
    exact hlarge B h0 hne hgcd hnp hnp1 hlt hpp p hp hnp2 hpn (hA p hp hnp2) ⟨a, ha, hpa⟩ hexb
  · push Not at hex
    exact hsmooth B h0 hne hgcd hnp hnp1 hlt hpp (fun p hp h a ha hpa => hex p hp h a ha hpa)
