import Mathlib
import Nodes.«erdos-402--h3-v2--h1--h1--h1».Context

open Filter

/-! Hole `hmid` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_402__h3_v2__h1__h1__h1 : ∀ (B : Finset ℕ),
  (0 : ℕ) ∉ B →
    B.Nonempty →
      B.gcd id = (1 : ℕ) →
        ¬Nat.Prime B.card →
          (∀ (q : ℕ), Nat.Prime q → B.card ≠ q + (1 : ℕ)) →
            (∀ a ∈ B, ∀ b ∈ B, a ≤ B.card * a.gcd b) →
              (∀ a ∈ B, ∀ (p k : ℕ), Nat.Prime p → p ^ k ∣ a → p ^ k < B.card) →
                (∃ a ∈ B, ∃ b ∈ B, (↑(a.gcd b) : ℚ) ≤ (↑a : ℚ) / (↑B.card : ℚ)) ∨
                  ∃ (p : ℕ), Nat.Prime p ∧ B.card ≤ (3 : ℕ) * p ∧ ∃ a ∈ B, p ∣ a := by
  -- Hole `hquarter`, two parts (one hole, a conjunction; n = |B|):
  -- (1) B has a pair with gcd(a, b) ≤ a / n, or an element with a prime factor p ≥ n / 4;
  -- (2) the kernel K3, a statement about two finite sets of positive integers, free of B:
  --     p prime, 3p < n ≤ 4p, X and S nonempty, each with all quotients x / gcd(x, x') < n, no member of S
  --     divisible by p, and every x in X, s in S with x·s·m = 6·y for some 1 ≤ m ≤ 3, y < n, p ∤ y, gcd(m, y) = 1.
  --     Then |X| + |S| ≤ n − 1.  (Equality holds for X = {2, 3, 6}, S = {s < n : p ∤ s}: the hypotheses are satisfiable.)
  -- The assembly (block_kernel) turns a set B with all quotients < n and a prime p, 3p < n ≤ 4p, dividing an element
  -- into such X (from the multiples of p) and S (from the others) with |X| + |S| = n.
  have hquarter : ∀ B : Finset ℕ, 0 ∉ B → B.Nonempty → B.gcd id = 1 → ¬ B.card.Prime →
      (∀ q : ℕ, q.Prime → B.card ≠ q + 1) →
      (∀ a ∈ B, ∀ b ∈ B, a ≤ B.card * a.gcd b) →
      (∀ a ∈ B, ∀ p k : ℕ, p.Prime → p ^ k ∣ a → p ^ k < B.card) →
      ((∃ a ∈ B, ∃ b ∈ B, (a.gcd b : ℚ) ≤ (a : ℚ) / (B.card : ℚ)) ∨
        ∃ p : ℕ, p.Prime ∧ B.card ≤ 4 * p ∧ ∃ a ∈ B, p ∣ a) ∧
      (∀ (n p : ℕ) (X S : Finset ℕ), p.Prime → 3 * p < n → n ≤ 4 * p → X.Nonempty → S.Nonempty →
        (∀ x ∈ X, 0 < x) → (∀ s ∈ S, 0 < s) → (∀ s ∈ S, ¬ p ∣ s) →
        (∀ x ∈ X, ∀ x' ∈ X, x < n * Nat.gcd x x') →
        (∀ s ∈ S, ∀ t ∈ S, s < n * Nat.gcd s t) →
        (∀ x ∈ X, ∀ s ∈ S, ∃ m y : ℕ, 0 < m ∧ m ≤ 3 ∧ y < n ∧ ¬ p ∣ y ∧ Nat.Coprime m y ∧
          x * s * m = 6 * y) →
        X.card + S.card < n) := sorry
  have R3c_block_kernel : ∀ (B : Finset ℕ) (N p M : ℕ) (h0 : 0 ∉ B) (hp : p.Prime) (hM0 : 0 < M) (hM : ∀ m : ℕ, 0 < m → m * p < N → m ∣ M) (hs : ∀ a ∈ B, ∀ b ∈ B, a < N * Nat.gcd a b) (hU : ∃ a ∈ B, p ∣ a) (hV : ∃ b ∈ B, ¬ p ∣ b),
      ∃ X S : Finset ℕ, X.card = (B.filter (fun a => p ∣ a)).card ∧ S.card = (B.filter (fun b => ¬ p ∣ b)).card ∧ (∀ x ∈ X, 0 < x) ∧ (∀ s ∈ S, 0 < s) ∧ (∀ s ∈ S, ¬ p ∣ s) ∧ (¬ p ∣ M → ∀ x ∈ X, ¬ p ∣ x) ∧ (∀ x ∈ X, ∀ x' ∈ X, x < N * Nat.gcd x x') ∧ (∀ s ∈ S, ∀ t ∈ S, s < N * Nat.gcd s t) ∧ (∀ x ∈ X, ∀ s ∈ S, ∃ m y : ℕ, 0 < m ∧ m * p < N ∧ y < N ∧ ¬ p ∣ y ∧ Nat.Coprime m y ∧ x * s * m = M * y) := by
    intro B N p M h0 hp hM0 hM hs hU hV
    have dual_quot : ∀ L a a' b b' : ℕ, a * a' = L → b * b' = L → 0 < a →
        a' * Nat.gcd a b = b * Nat.gcd a' b' := by
      intro L a a' b b' ha hb h0
      have h1 : Nat.gcd a' b' * (a * b) = L * Nat.gcd a b := by
        rw [← Nat.gcd_mul_right]
        have e1 : a' * (a * b) = L * b := by rw [← ha]; ring
        have e2 : b' * (a * b) = L * a := by rw [← hb]; ring
        rw [e1, e2, Nat.gcd_mul_left, Nat.gcd_comm b a]
      have h2 : a * (a' * Nat.gcd a b) = a * (b * Nat.gcd a' b') := by
        rw [← mul_assoc, ha, ← h1]; ring
      exact Nat.eq_of_mul_eq_mul_left h0 h2
    have hpos : ∀ a ∈ B, 0 < a := fun a ha => Nat.pos_of_ne_zero (fun e => h0 (e ▸ ha))
    generalize hG : (B.filter (fun b => ¬ p ∣ b)).gcd id = G
    have hGb : ∀ b ∈ B, ¬ p ∣ b → G ∣ b := by
      intro b hb hpb
      rw [← hG]
      exact Finset.gcd_dvd (f := id) (Finset.mem_filter.mpr ⟨hb, hpb⟩)
    obtain ⟨a0, ha0B, hpa0⟩ := hU
    obtain ⟨b0, hb0B, hpb0⟩ := hV
    have hG0 : 0 < G := Nat.pos_of_dvd_of_pos (hGb b0 hb0B hpb0) (hpos b0 hb0B)
    have hpG : ¬ p ∣ G := fun h => hpb0 (h.trans (hGb b0 hb0B hpb0))
    -- the pair analysis
    have hpair : ∀ a ∈ B, p ∣ a → ∀ b ∈ B, ¬ p ∣ b →
        ∃ m y : ℕ, 0 < m ∧ m * p < N ∧ y < N ∧ ¬ p ∣ y ∧ Nat.Coprime m y ∧ a * y = p * m * b := by
      intro a ha hpa b hb hpb
      have hg0 : 0 < a.gcd b := Nat.gcd_pos_of_pos_left b (hpos a ha)
      obtain ⟨x, hx⟩ := Nat.gcd_dvd_left a b
      obtain ⟨y, hy⟩ := Nat.gcd_dvd_right a b
      have hcop : Nat.Coprime x y := by
        have h := Nat.coprime_div_gcd_div_gcd hg0
        rwa [Nat.div_eq_of_eq_mul_right hg0 hx, Nat.div_eq_of_eq_mul_right hg0 hy] at h
      have hpg : ¬ p ∣ a.gcd b := fun h => hpb (h.trans (Nat.gcd_dvd_right a b))
      have hpx : p ∣ x := by
        have h1 : p ∣ a.gcd b * x := hx ▸ hpa
        exact (hp.dvd_mul.mp h1).resolve_left hpg
      obtain ⟨m, hm⟩ := hpx
      have hxN : x < N := by
        have h1 := hs a ha b hb
        have h3 : a.gcd b * x < a.gcd b * N := by
          rw [← hx, Nat.mul_comm]; exact h1
        exact Nat.lt_of_mul_lt_mul_left h3
      have hyN : y < N := by
        have h1 := hs b hb a ha
        rw [Nat.gcd_comm b a] at h1
        have h3 : a.gcd b * y < a.gcd b * N := by
          rw [← hy, Nat.mul_comm]; exact h1
        exact Nat.lt_of_mul_lt_mul_left h3
      have hx0 : 0 < x := Nat.pos_of_ne_zero (by
        rintro rfl
        rw [Nat.mul_zero] at hx
        exact (hpos a ha).ne' hx)
      have hm0 : 0 < m := Nat.pos_of_ne_zero (by
        rintro rfl
        rw [Nat.mul_zero] at hm
        exact hx0.ne' hm)
      refine ⟨m, y, hm0, by rw [Nat.mul_comm, ← hm]; exact hxN, hyN, ?_, ?_, ?_⟩
      · exact fun h => hpb (h.trans ⟨a.gcd b, by rw [Nat.mul_comm]; exact hy⟩)
      · rw [hm] at hcop
        exact Nat.Coprime.coprime_mul_left hcop
      · calc a * y = a.gcd b * x * y := by rw [← hx]
          _ = p * m * (a.gcd b * y) := by rw [hm]; ring
          _ = p * m * b := by rw [← hy]
    -- every multiple of p divides p * M * G
    have hdiv : ∀ a ∈ B, p ∣ a → a ∣ p * M * G := by
      intro a ha hpa
      have h1 : a ∣ (B.filter (fun b => ¬ p ∣ b)).gcd (fun b => p * M * id b) := by
        apply Finset.dvd_gcd
        intro b hb
        obtain ⟨hbB, hpb⟩ := Finset.mem_filter.mp hb
        obtain ⟨m, y, hm0, hmp, -, -, -, e⟩ := hpair a ha hpa b hbB hpb
        obtain ⟨m', hm'⟩ := hM m hm0 hmp
        exact ⟨y * m', by
          show p * M * b = a * (y * m')
          rw [← Nat.mul_assoc, e, hm']; ring⟩
      rw [Finset.gcd_mul_left, hG] at h1
      simpa using h1
    have hLpos : 0 < p * M * G := Nat.mul_pos (Nat.mul_pos hp.pos hM0) hG0
    have hax : ∀ a ∈ B, p ∣ a → a * (p * M * G / a) = p * M * G :=
      fun a ha hpa => Nat.mul_div_cancel' (hdiv a ha hpa)
    have hxpos : ∀ a ∈ B, p ∣ a → 0 < p * M * G / a := by
      intro a ha hpa
      exact Nat.pos_of_ne_zero (by
        intro h
        have e1 := hax a ha hpa
        rw [h, Nat.mul_zero] at e1
        exact hLpos.ne e1)
    have hbs : ∀ b ∈ B, ¬ p ∣ b → G * (b / G) = b :=
      fun b hb hpb => Nat.mul_div_cancel' (hGb b hb hpb)
    have hspos : ∀ b ∈ B, ¬ p ∣ b → 0 < b / G := by
      intro b hb hpb
      exact Nat.pos_of_ne_zero (by
        intro h
        have e2 := hbs b hb hpb
        rw [h, Nat.mul_zero] at e2
        exact (hpos b hb).ne e2)
    have hinjX : Set.InjOn (fun a => p * M * G / a) (B.filter (fun a => p ∣ a) : Finset ℕ) := by
      intro a ha a' ha' h
      obtain ⟨haB, hpa⟩ := Finset.mem_filter.mp ha
      obtain ⟨haB', hpa'⟩ := Finset.mem_filter.mp ha'
      have h1 := hax a haB hpa
      have h2 := hax a' haB' hpa'
      simp only at h
      rw [← h] at h2
      exact Nat.eq_of_mul_eq_mul_right (hxpos a haB hpa) (h1.trans h2.symm)
    have hinjT : Set.InjOn (fun b => b / G) (B.filter (fun b => ¬ p ∣ b) : Finset ℕ) := by
      intro b hb b' hb' h
      obtain ⟨hbB, hpb⟩ := Finset.mem_filter.mp hb
      obtain ⟨hbB', hpb'⟩ := Finset.mem_filter.mp hb'
      simp only at h
      rw [← Nat.div_mul_cancel (hGb b hbB hpb), ← Nat.div_mul_cancel (hGb b' hbB' hpb'), h]
    refine ⟨(B.filter (fun a => p ∣ a)).image (fun a => p * M * G / a),
      (B.filter (fun b => ¬ p ∣ b)).image (fun b => b / G),
      Finset.card_image_of_injOn hinjX, Finset.card_image_of_injOn hinjT, ?_, ?_, ?_, ?_, ?_, ?_, ?_⟩
    · intro x hx
      obtain ⟨a, ha, rfl⟩ := Finset.mem_image.mp hx
      obtain ⟨haB, hpa⟩ := Finset.mem_filter.mp ha
      exact hxpos a haB hpa
    · intro s hs'
      obtain ⟨b, hb, rfl⟩ := Finset.mem_image.mp hs'
      obtain ⟨hbB, hpb⟩ := Finset.mem_filter.mp hb
      exact hspos b hbB hpb
    · intro s hs' hps
      obtain ⟨b, hb, rfl⟩ := Finset.mem_image.mp hs'
      obtain ⟨hbB, hpb⟩ := Finset.mem_filter.mp hb
      exact hpb (hps.trans ⟨G, by rw [Nat.mul_comm]; exact (hbs b hbB hpb).symm⟩)
    · intro hpM x hx hpx
      obtain ⟨a, ha, rfl⟩ := Finset.mem_image.mp hx
      obtain ⟨haB, hpa⟩ := Finset.mem_filter.mp ha
      obtain ⟨c, hc⟩ := hpa
      obtain ⟨d, hd⟩ := hpx
      have e := hax a haB ⟨c, hc⟩
      rw [hd] at e
      have h3 : p * (p * (c * d)) = p * (M * G) := by
        rw [← Nat.mul_assoc p M G, ← e, hc]; ring
      have h4 : p ∣ M * G := ⟨c * d, (Nat.eq_of_mul_eq_mul_left hp.pos h3).symm⟩
      rcases hp.dvd_mul.mp h4 with h5 | h5
      · exact hpM h5
      · exact hpG h5
    · intro x hx x' hx'
      obtain ⟨a, ha, rfl⟩ := Finset.mem_image.mp hx
      obtain ⟨a', ha', rfl⟩ := Finset.mem_image.mp hx'
      obtain ⟨haB, hpa⟩ := Finset.mem_filter.mp ha
      obtain ⟨haB', hpa'⟩ := Finset.mem_filter.mp ha'
      have e := dual_quot (p * M * G) a (p * M * G / a) a' (p * M * G / a')
        (hax a haB hpa) (hax a' haB' hpa') (hpos a haB)
      have h1 := hs a' haB' a haB
      rw [Nat.gcd_comm a' a] at h1
      have hg : 0 < Nat.gcd a a' := Nat.gcd_pos_of_pos_left _ (hpos a haB)
      have h2 : (p * M * G / a) * Nat.gcd a a'
          < (N * Nat.gcd (p * M * G / a) (p * M * G / a')) * Nat.gcd a a' := by
        rw [e]
        calc a' * Nat.gcd (p * M * G / a) (p * M * G / a')
            < N * Nat.gcd a a' * Nat.gcd (p * M * G / a) (p * M * G / a') :=
              Nat.mul_lt_mul_of_pos_right h1
                (Nat.gcd_pos_of_pos_left _ (hxpos a haB hpa))
          _ = (N * Nat.gcd (p * M * G / a) (p * M * G / a')) * Nat.gcd a a' := by ring
      exact Nat.lt_of_mul_lt_mul_right h2
    · intro s hs' t ht
      obtain ⟨b, hb, rfl⟩ := Finset.mem_image.mp hs'
      obtain ⟨b', hb', rfl⟩ := Finset.mem_image.mp ht
      obtain ⟨hbB, hpb⟩ := Finset.mem_filter.mp hb
      obtain ⟨hbB', hpb'⟩ := Finset.mem_filter.mp hb'
      have h1 := hs b hbB b' hbB'
      have e1 := hbs b hbB hpb
      have e2 := hbs b' hbB' hpb'
      have h2 : G * (b / G) < G * (N * Nat.gcd (b / G) (b' / G)) := by
        calc G * (b / G) = b := e1
          _ < N * Nat.gcd b b' := h1
          _ = N * Nat.gcd (G * (b / G)) (G * (b' / G)) := by rw [e1, e2]
          _ = G * (N * Nat.gcd (b / G) (b' / G)) := by rw [Nat.gcd_mul_left]; ring
      exact Nat.lt_of_mul_lt_mul_left h2
    · intro x hx s hs'
      obtain ⟨a, ha, rfl⟩ := Finset.mem_image.mp hx
      obtain ⟨b, hb, rfl⟩ := Finset.mem_image.mp hs'
      obtain ⟨haB, hpa⟩ := Finset.mem_filter.mp ha
      obtain ⟨hbB, hpb⟩ := Finset.mem_filter.mp hb
      obtain ⟨m, y, hm0, hmp, hyN, hpy, hcop, e⟩ := hpair a haB hpa b hbB hpb
      refine ⟨m, y, hm0, hmp, hyN, hpy, hcop, ?_⟩
      have e1 := hax a haB hpa
      have e2 := hbs b hbB hpb
      have h3 : (a * G) * ((p * M * G / a) * (b / G) * m) = (a * G) * (M * y) := by
        calc (a * G) * ((p * M * G / a) * (b / G) * m)
            = (a * (p * M * G / a)) * (G * (b / G)) * m := by ring
          _ = p * M * G * b * m := by rw [e1, e2]
          _ = M * G * (p * m * b) := by ring
          _ = M * G * (a * y) := by rw [e]
          _ = (a * G) * (M * y) := by ring
      exact Nat.eq_of_mul_eq_mul_left (Nat.mul_pos (hpos a haB) hG0) h3
  have R3c_no_prime_of_kernel : ∀ (B : Finset ℕ) (h0 : 0 ∉ B) (hgcd : B.gcd id = 1) (hlt : ∀ a ∈ B, ∀ b ∈ B, a < B.card * a.gcd b) (p k M : ℕ) (hp : p.Prime) (hM0 : 0 < M) (hM : ∀ m : ℕ, 0 < m → m ≤ k → m ∣ M) (hk : B.card ≤ (k + 1) * p) (hK : ∀ X S : Finset ℕ, X.Nonempty → S.Nonempty → (∀ x ∈ X, 0 < x) → (∀ s ∈ S, 0 < s) → (∀ s ∈ S, ¬ p ∣ s) → (∀ x ∈ X, ∀ x' ∈ X, x < B.card * Nat.gcd x x') → (∀ s ∈ S, ∀ t ∈ S, s < B.card * Nat.gcd s t) → (∀ x ∈ X, ∀ s ∈ S, ∃ m y : ℕ, 0 < m ∧ m ≤ k ∧ y < B.card ∧ ¬ p ∣ y ∧ Nat.Coprime m y ∧ x * s * m = M * y) → X.card + S.card < B.card),
      ∀ a ∈ B, ¬ p ∣ a := by
    intro B h0 hgcd hlt p k M hp hM0 hM hk hK
    intro a0 ha0 hpa0
    have hV : ∃ b ∈ B, ¬ p ∣ b := by
      by_contra h
      push Not at h
      have h1 : p ∣ B.gcd id := Finset.dvd_gcd (fun b hb => h b hb)
      rw [hgcd] at h1
      exact hp.one_lt.ne' (Nat.dvd_one.mp h1)
    have hmk : ∀ m : ℕ, m * p < B.card → m ≤ k := by
      intro m hmp
      by_contra hcon
      push Not at hcon
      have : (k + 1) * p ≤ m * p := Nat.mul_le_mul_right p hcon
      omega
    obtain ⟨X, S, hXc, hSc, hX0, hS0, hSp, -, hXX, hSS, hXS⟩ :=
      R3c_block_kernel B B.card p M h0 hp hM0 (fun m hm0 hmp => hM m hm0 (hmk m hmp)) hlt
        ⟨a0, ha0, hpa0⟩ hV
    have hsum : (B.filter (fun a => p ∣ a)).card + (B.filter (fun b => ¬ p ∣ b)).card = B.card := by
      rw [← Finset.card_union_of_disjoint (Finset.disjoint_filter_filter_not B B (fun a => p ∣ a)),
        Finset.filter_union_filter_not_eq]
    have hXne : X.Nonempty := by
      rw [← Finset.card_pos, hXc, Finset.card_pos]
      exact ⟨a0, Finset.mem_filter.mpr ⟨ha0, hpa0⟩⟩
    have hSne : S.Nonempty := by
      obtain ⟨b, hb, hpb⟩ := hV
      rw [← Finset.card_pos, hSc, Finset.card_pos]
      exact ⟨b, Finset.mem_filter.mpr ⟨hb, hpb⟩⟩
    have := hK X S hXne hSne hX0 hS0 hSp hXX hSS (by
      intro x hx s hs
      obtain ⟨m, y, hm0, hmp, hy, hpy, hc, e⟩ := hXS x hx s hs
      exact ⟨m, y, hm0, hmk m hmp, hy, hpy, hc, e⟩)
    omega
  have R3c_no_quarter_prime : ∀ (B : Finset ℕ) (h0 : 0 ∉ B) (hgcd : B.gcd id = 1) (hlt : ∀ a ∈ B, ∀ b ∈ B, a < B.card * a.gcd b) (p : ℕ) (hp : p.Prime) (h3p : 3 * p < B.card) (hn4 : B.card ≤ 4 * p) (hK3 : ∀ (n p : ℕ) (X S : Finset ℕ), p.Prime → 3 * p < n → n ≤ 4 * p → X.Nonempty → S.Nonempty → (∀ x ∈ X, 0 < x) → (∀ s ∈ S, 0 < s) → (∀ s ∈ S, ¬ p ∣ s) → (∀ x ∈ X, ∀ x' ∈ X, x < n * Nat.gcd x x') → (∀ s ∈ S, ∀ t ∈ S, s < n * Nat.gcd s t) → (∀ x ∈ X, ∀ s ∈ S, ∃ m y : ℕ, 0 < m ∧ m ≤ 3 ∧ y < n ∧ ¬ p ∣ y ∧ Nat.Coprime m y ∧ x * s * m = 6 * y) → X.card + S.card < n),
      ∀ a ∈ B, ¬ p ∣ a := by
    intro B h0 hgcd hlt p hp h3p hn4 hK3
    refine R3c_no_prime_of_kernel B h0 hgcd hlt p 3 6 hp (by norm_num) ?_ hn4
      (fun X S => hK3 B.card p X S hp h3p hn4)
    intro m hm0 hm3
    interval_cases m <;> norm_num
  intro B h0 hne hgcd hnp hnp1 hle hpp
  obtain ⟨h1, hK3⟩ := hquarter B h0 hne hgcd hnp hnp1 hle hpp
  rcases h1 with h | ⟨p, hp, hn4, a, ha, hpa⟩
  · exact Or.inl h
  by_cases h3 : B.card ≤ 3 * p
  · exact Or.inr ⟨p, hp, h3, a, ha, hpa⟩
  left
  by_contra hcon
  have hnq : (0 : ℚ) < B.card := by exact_mod_cast hne.card_pos
  have hlt : ∀ a ∈ B, ∀ b ∈ B, a < B.card * a.gcd b := by
    intro a ha b hb
    rcases (hle a ha b hb).lt_or_eq with h | h
    · exact h
    · exfalso
      apply hcon
      refine ⟨a, ha, b, hb, ?_⟩
      rw [le_div_iff₀ hnq]
      have h2 : a.gcd b * B.card ≤ a := by rw [Nat.mul_comm]; exact h.ge
      exact_mod_cast h2
  exact R3c_no_quarter_prime B h0 hgcd hlt p hp (by omega) hn4 hK3 a ha hpa
