import Mathlib
import Nodes.«erdos-1050--h1-v2--h4».Context

/-! Hole `hrem` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_1050__h1_v2__h4 : ∀ (Qc : ℕ → ℕ → ℚ),
  (Qc = fun (n k : ℕ) =>
      ((-1 : ℚ) ^ k * (2 : ℚ) ^ (k * (k - (1 : ℕ)) / (2 : ℕ)) *
          ∏ i ∈ Finset.range k, ((2 : ℚ) ^ (n - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) *
        ∏ i ∈ Finset.range n, ((2 : ℚ) ^ ((2 : ℕ) * n - k - i) - (1 : ℚ)) / ((2 : ℚ) ^ (i + (1 : ℕ)) - (1 : ℚ))) →
    ∀ (Qx : ℕ → ℚ),
      (Qx = fun (n : ℕ) => ∑ k ∈ Finset.range (n + (1 : ℕ)), Qc n k * ((3 : ℚ) / (2 : ℚ) ^ n) ^ k) →
        ∀ (Aq : ℕ → ℚ),
          (Aq = fun (n : ℕ) =>
              ∑ k ∈ Finset.range (n + (1 : ℕ)),
                  (∑ j ∈ Finset.range (k + (1 : ℕ)), Qc n j / ((2 : ℚ) ^ (k - j) - (1 : ℚ))) *
                    ((3 : ℚ) / (2 : ℚ) ^ n) ^ k +
                Qx n * ∑ j ∈ Finset.range n, (3 : ℚ) / ((2 : ℚ) ^ (j + (1 : ℕ)) - (3 : ℚ))) →
            (∀ (n : ℕ),
                ∃ (d : ℕ),
                  (0 : ℕ) < d ∧
                    (↑d : ℝ) ^ (2 : ℕ) ≤ (2 : ℝ) ^ ((3 : ℕ) * n * n) ∧
                      (∃ (z : ℤ), (↑z : ℚ) = (↑d : ℚ) * Qx n) ∧ ∃ (z : ℤ), (↑z : ℚ) = (↑d : ℚ) * Aq n) →
              ∀ (n : ℕ),
                (0 : ℝ) <
                    (↑(Qx n) : ℝ) * ((3 : ℝ) * ∑' (n : ℕ), (1 : ℝ) / ((2 : ℝ) ^ (n + (3 : ℕ)) - (3 : ℝ))) -
                      (↑(Aq n) : ℝ) ∧
                  ((↑(Qx n) : ℝ) * ((3 : ℝ) * ∑' (n : ℕ), (1 : ℝ) / ((2 : ℝ) ^ (n + (3 : ℕ)) - (3 : ℝ))) -
                          (↑(Aq n) : ℝ)) ^
                        (2 : ℕ) *
                      (2 : ℝ) ^ ((4 : ℕ) * n * n) ≤
                    (2 : ℝ) ^ ((2 : ℕ) * n + (4 : ℕ)) := by
  intro Qc hQc Qx hQx Aq hAq _hden n
  obtain ⟨T, hT⟩ : ∃ T : ℝ, T = ∑' (n : ℕ), (1 : ℝ) / ((2 : ℝ) ^ (n + (3 : ℕ)) - (3 : ℝ)) := ⟨_, rfl⟩
  rw [← hT]
  -- the terms of T are bounded by (1/5) (1/2)^m
  have hterm : ∀ m : ℕ, 0 ≤ (1 : ℝ) / ((2 : ℝ) ^ (m + 3) - 3) ∧
      (1 : ℝ) / ((2 : ℝ) ^ (m + 3) - 3) ≤ (1 / 5 : ℝ) * (1 / 2 : ℝ) ^ m := by
    intro m
    have h2 : (1 : ℝ) ≤ (2 : ℝ) ^ m := one_le_pow₀ (by norm_num)
    have hpos : (0 : ℝ) < (2 : ℝ) ^ (m + 3) - 3 := by rw [pow_add]; nlinarith
    refine ⟨div_nonneg zero_le_one hpos.le, ?_⟩
    rw [div_le_iff₀ hpos]
    have hh : (1 / 2 : ℝ) ^ m * (2 : ℝ) ^ m = 1 := by rw [← mul_pow]; norm_num
    have hle : (1 / 2 : ℝ) ^ m ≤ 1 := pow_le_one₀ (by norm_num) (by norm_num)
    rw [pow_add]
    nlinarith
  have hgeo : Summable (fun m : ℕ => (1 / 5 : ℝ) * (1 / 2 : ℝ) ^ m) :=
    (summable_geometric_of_lt_one (by norm_num) (by norm_num)).mul_left _
  have hsumm : Summable (fun m : ℕ => (1 : ℝ) / ((2 : ℝ) ^ (m + (3 : ℕ)) - (3 : ℝ))) :=
    Summable.of_nonneg_of_le (fun m => (hterm m).1) (fun m => (hterm m).2) hgeo
  have hTpos : 0 < T := by
    rw [hT]
    exact hsumm.tsum_pos (fun m => (hterm m).1) 0 (by norm_num)
  have hTle : T ≤ 2 / 5 := by
    rw [hT]
    calc ∑' (n : ℕ), (1 : ℝ) / ((2 : ℝ) ^ (n + (3 : ℕ)) - (3 : ℝ))
        ≤ ∑' m : ℕ, (1 / 5 : ℝ) * (1 / 2 : ℝ) ^ m :=
          Summable.tsum_le_tsum (fun m => (hterm m).2) hsumm hgeo
      _ = 2 / 5 := by rw [tsum_mul_left, tsum_geometric_of_lt_one (by norm_num) (by norm_num)]; norm_num
  -- the Padé remainder coefficients, in closed form (spec-f2b55478), shifted to start at x^(2n+1)
  obtain ⟨E, hE⟩ : ∃ E : ℕ → ℕ → ℝ, E = fun n t =>
      (2 : ℝ) ^ (n * n) * (∏ i ∈ Finset.range n, ((2 : ℝ) ^ (n + t - i) - 1)) /
        ∏ j ∈ Finset.range (n + 1), ((2 : ℝ) ^ (2 * n + 1 + t - j) - 1) := ⟨_, rfl⟩
  have hEpos : ∀ n t : ℕ, 0 < E n t := by
    sorry
  have hEle : ∀ n t : ℕ, E n t ≤ (1 / 2 : ℝ) ^ (2 * n + t) := by
    sorry
  -- the one hole: the Padé remainder as a series of positive terms
  have hser : ∀ n : ℕ, 2 ≤ n →
      HasSum (fun t : ℕ => E n t * ((3 : ℝ) / (2 : ℝ) ^ n) ^ (2 * n + 1 + t))
        ((Qx n : ℝ) * (3 * T) - (Aq n : ℝ)) := by
    sorry
  rcases (show n = 0 ∨ n = 1 ∨ 2 ≤ n by omega) with rfl | rfl | hn
  · have hq : Qx 0 = 1 := by rw [hQx, hQc]; simp
    have ha : Aq 0 = 0 := by rw [hAq, hQx, hQc]; simp
    rw [hq, ha]
    push_cast
    constructor <;> nlinarith
  · have hq : Qx 1 = 3 / 2 := by
      rw [hQx, hQc]; simp [Finset.sum_range_succ, Finset.prod_range_succ]; norm_num
    have ha : Aq 1 = 0 := by
      rw [hAq, hQx, hQc]; simp [Finset.sum_range_succ, Finset.prod_range_succ]; norm_num
    rw [hq, ha]
    push_cast
    constructor <;> nlinarith
  · have hs := hser n hn
    have hy4 : (4 : ℝ) ≤ (2 : ℝ) ^ n := by
      calc (4 : ℝ) = 2 ^ 2 := by norm_num
        _ ≤ 2 ^ n := pow_le_pow_right₀ (by norm_num) hn
    have hw : 3 * ((3 : ℝ) ^ n) ^ 2 ≤ 2 * ((2 : ℝ) ^ n) ^ 4 := by
      obtain ⟨k, hk⟩ : ∃ k, n = k + 2 := ⟨n - 2, by omega⟩
      have h916 : (9 : ℝ) ^ k ≤ 16 ^ k := pow_le_pow_left₀ (by norm_num) (by norm_num) k
      have e1 : ((3 : ℝ) ^ n) ^ 2 = 81 * 9 ^ k := by
        have h9 : (9 : ℝ) ^ k = ((3 : ℝ) ^ k) ^ 2 := by rw [← pow_mul, mul_comm, pow_mul]; norm_num
        rw [hk, h9]; ring
      have e2 : ((2 : ℝ) ^ n) ^ 4 = 256 * 16 ^ k := by
        have h16 : (16 : ℝ) ^ k = ((2 : ℝ) ^ k) ^ 4 := by rw [← pow_mul, mul_comm, pow_mul]; norm_num
        rw [hk, h16]; ring
      rw [e1, e2]; nlinarith
    have hbound : ∀ t : ℕ, E n t * ((3 : ℝ) / (2 : ℝ) ^ n) ^ (2 * n + 1 + t) ≤
        (2 : ℝ) ^ (n + 1) / ((2 : ℝ) ^ n) ^ (2 * n) * (1 / 2 : ℝ) ^ t := by
      intro t
      have hu : (3 : ℝ) ^ t ≤ ((2 : ℝ) ^ n) ^ t := pow_le_pow_left₀ (by norm_num) (by linarith) t
      have hyp : (0 : ℝ) < (2 : ℝ) ^ n := by positivity
      calc E n t * ((3 : ℝ) / (2 : ℝ) ^ n) ^ (2 * n + 1 + t)
          ≤ (1 / 2 : ℝ) ^ (2 * n + t) * ((3 : ℝ) / (2 : ℝ) ^ n) ^ (2 * n + 1 + t) :=
            mul_le_mul_of_nonneg_right (hEle n t) (by positivity)
        _ = 3 * ((3 : ℝ) ^ n) ^ 2 * 3 ^ t /
              (((2 : ℝ) ^ n) ^ 2 * 2 ^ t * (((2 : ℝ) ^ n) ^ (2 * n) * (2 : ℝ) ^ n * ((2 : ℝ) ^ n) ^ t)) := by
            rw [one_div_pow, div_pow]
            field_simp
            try ring
        _ ≤ 2 * ((2 : ℝ) ^ n) ^ 4 * ((2 : ℝ) ^ n) ^ t /
              (((2 : ℝ) ^ n) ^ 2 * 2 ^ t * (((2 : ℝ) ^ n) ^ (2 * n) * (2 : ℝ) ^ n * ((2 : ℝ) ^ n) ^ t)) := by
            gcongr
        _ = (2 : ℝ) ^ (n + 1) / ((2 : ℝ) ^ n) ^ (2 * n) * (1 / 2 : ℝ) ^ t := by
            rw [one_div_pow]
            field_simp
            try ring
    have hgeomS : HasSum (fun t : ℕ => (2 : ℝ) ^ (n + 1) / ((2 : ℝ) ^ n) ^ (2 * n) * (1 / 2 : ℝ) ^ t)
        ((2 : ℝ) ^ (n + 1) / ((2 : ℝ) ^ n) ^ (2 * n) * (1 - 1 / 2)⁻¹) :=
      (hasSum_geometric_of_lt_one (by norm_num) (by norm_num)).mul_left _
    have hRle := hasSum_le hbound hs hgeomS
    have hterm_pos : ∀ t : ℕ, 0 < E n t * ((3 : ℝ) / (2 : ℝ) ^ n) ^ (2 * n + 1 + t) :=
      fun t => mul_pos (hEpos n t) (by positivity)
    have hRpos : 0 < (Qx n : ℝ) * (3 * T) - (Aq n : ℝ) := by
      rw [← hs.tsum_eq]
      exact hs.summable.tsum_pos (fun t => (hterm_pos t).le) 0 (hterm_pos 0)
    refine ⟨hRpos, ?_⟩
    have hB : (2 : ℝ) ^ (n + 1) / ((2 : ℝ) ^ n) ^ (2 * n) * (1 - 1 / 2)⁻¹ =
        (2 : ℝ) ^ (n + 2) / ((2 : ℝ) ^ n) ^ (2 * n) := by
      field_simp; ring
    rw [hB] at hRle
    have hpow : (2 : ℝ) ^ (4 * n * n) = (((2 : ℝ) ^ n) ^ (2 * n)) ^ 2 := by
      rw [← pow_mul, ← pow_mul]; ring_nf
    have hQ : (0 : ℝ) < ((2 : ℝ) ^ n) ^ (2 * n) := by positivity
    rw [hpow]
    calc ((Qx n : ℝ) * (3 * T) - (Aq n : ℝ)) ^ 2 * (((2 : ℝ) ^ n) ^ (2 * n)) ^ 2
        = (((Qx n : ℝ) * (3 * T) - (Aq n : ℝ)) * ((2 : ℝ) ^ n) ^ (2 * n)) ^ 2 := by ring
      _ ≤ ((2 : ℝ) ^ (n + 2)) ^ 2 := by
          gcongr
          rw [le_div_iff₀ hQ] at hRle; exact hRle
      _ = (2 : ℝ) ^ (2 * n + 4) := by ring
