import Mathlib

open Filter

/-! Hole `h3` of a merged partial proof, as a node (D-12 #5, D-29).
Statement generated by the gate from the assembly; immutable (D-3). -/

theorem erdos_402__h3 : (∀ (A : Finset ℕ) (m : ℕ),
    0 ∉ A →
      (∀ a ∈ A, ∀ b ∈ A, a ≤ m * a.gcd b) →
        ∀ a ∈ A, ∀ b ∈ A, ∃ u v, 0 < u ∧ u ≤ m ∧ 0 < v ∧ v ≤ m ∧ u.Coprime v ∧ a * v = b * u) →
  (∀ (A : Finset ℕ),
      0 ∉ A →
        A.Nonempty →
          (∀ (B : Finset ℕ), 0 ∉ B → B.card = A.card → B.gcd id = 1 → ∃ a ∈ B, ∃ b ∈ B, a.gcd b ≤ (a / B.card : ℚ)) →
            ∃ a ∈ A, ∃ b ∈ A, a.gcd b ≤ (a / A.card : ℚ)) →
    ∀ (A : Finset ℕ),
      0 ∉ A →
        A.Nonempty →
          A.gcd id = 1 →
            (∀ a ∈ A, ∀ b ∈ A, ∃ u v, 0 < u ∧ u ≤ A.card ∧ 0 < v ∧ v ≤ A.card ∧ u.Coprime v ∧ a * v = b * u) →
              ∃ a ∈ A, ∃ b ∈ A, a.gcd b ≤ (a / A.card : ℚ) := by
  -- annex: f5450271cb4865766831f2e6b153cb532934219590cff79ed42bb2ff813b15ac
  -- Hole (composite size): Graham's bound for a primitive set of composite size n whose
  -- quotients a / gcd(a, b) are at most n and every prime power dividing an element is below n.
  -- This is where Balasubramanian–Soundararajan (1996) is still needed.
  have hcomp : ∀ B : Finset ℕ, 0 ∉ B → B.Nonempty → B.gcd id = 1 → ¬ B.card.Prime →
      (∀ a ∈ B, ∀ b ∈ B, a ≤ B.card * a.gcd b) →
      (∀ a ∈ B, ∀ p k : ℕ, p.Prime → p ^ k ∣ a → p ^ k < B.card) →
      ∃ a ∈ B, ∃ b ∈ B, a.gcd b ≤ (a / B.card : ℚ) := sorry
  intro _hh1 _hh2 A hA hne hg _hfarey
  by_contra hcon
  push Not at hcon
  have hn : 0 < A.card := hne.card_pos
  have hnq : (0 : ℚ) < A.card := by exact_mod_cast hn
  -- If the bound fails, every quotient a / gcd(a, b) is below n = |A|.
  have hlt : ∀ a ∈ A, ∀ b ∈ A, a < A.card * a.gcd b := by
    intro a ha b hb
    have h' : (a : ℚ) < (a.gcd b : ℚ) * A.card := (div_lt_iff₀ hnq).mp (hcon a ha b hb)
    have h'' : (a : ℚ) < ((A.card * a.gcd b : ℕ) : ℚ) := by push_cast; linarith
    exact_mod_cast h''
  -- Prime powers: since gcd A = 1 some b is prime to p, and p ^ k divides a / gcd(a, b) < n.
  have hpp : ∀ a ∈ A, ∀ p k : ℕ, p.Prime → p ^ k ∣ a → p ^ k < A.card := by
    intro a ha p k hp hdvd
    obtain ⟨b, hb, hpb⟩ : ∃ b ∈ A, ¬ p ∣ b := by
      by_contra h
      push Not at h
      have h1 : p ∣ A.gcd id := Finset.dvd_gcd (fun b hb => h b hb)
      rw [hg] at h1
      exact hp.one_lt.ne' (Nat.dvd_one.mp h1)
    have ha0 : a ≠ 0 := fun h => hA (h ▸ ha)
    have hg0 : 0 < a.gcd b := Nat.gcd_pos_of_pos_left b (Nat.pos_of_ne_zero ha0)
    obtain ⟨x, hx⟩ := Nat.gcd_dvd_left a b
    have hcop : Nat.Coprime (p ^ k) (a.gcd b) := by
      apply Nat.Coprime.pow_left
      rw [Nat.Prime.coprime_iff_not_dvd hp]
      intro h
      exact hpb (h.trans (Nat.gcd_dvd_right a b))
    have hdx : p ^ k ∣ x := by
      have h1 : p ^ k ∣ a.gcd b * x := hx ▸ hdvd
      exact hcop.dvd_of_dvd_mul_left h1
    have hx0 : x ≠ 0 := by
      rintro rfl
      rw [mul_zero] at hx
      exact ha0 hx
    have hxlt : x < A.card := by
      have h2 : a.gcd b * x < a.gcd b * A.card := by
        rw [← hx, mul_comm]
        exact hlt a ha b hb
      exact Nat.lt_of_mul_lt_mul_left h2
    exact lt_of_le_of_lt (Nat.le_of_dvd (Nat.pos_of_ne_zero hx0) hdx) hxlt
  by_cases hpr : A.card.Prime
  · -- Prime size n = p: no element is divisible by p (p ^ 1 < p fails), so a ↦ a % p maps the p
    -- elements into the p - 1 non-zero residues. Two elements a ≠ b collide; with g = gcd(a, b),
    -- a = g x and b = g y where x, y < p and p ∤ g, so x ≡ y (mod p) forces x = y and a = b.
    have hnd : ∀ a ∈ A, ¬ A.card ∣ a := by
      intro a ha h
      have h1 := hpp a ha A.card 1 hpr (by rw [pow_one]; exact h)
      rw [pow_one] at h1
      exact lt_irrefl _ h1
    have hmaps : Set.MapsTo (fun a => a % A.card) (A : Set ℕ) (Finset.Icc 1 (A.card - 1) : Set ℕ) := by
      intro a ha
      have ha' : a ∈ A := ha
      have h1 : a % A.card < A.card := Nat.mod_lt a hn
      have h2 : a % A.card ≠ 0 := fun h => hnd a ha' (Nat.dvd_of_mod_eq_zero h)
      simp only [Finset.coe_Icc, Set.mem_Icc]
      omega
    have hcard : (Finset.Icc 1 (A.card - 1)).card < A.card := by
      rw [Nat.card_Icc]
      omega
    obtain ⟨a, ha, b, hb, hab, heq⟩ := Finset.exists_ne_map_eq_of_card_lt_of_maps_to hcard hmaps
    obtain ⟨x, hx⟩ := Nat.gcd_dvd_left a b
    obtain ⟨y, hy⟩ := Nat.gcd_dvd_right a b
    have hxlt : x < A.card := by
      have h2 : a.gcd b * x < a.gcd b * A.card := by
        rw [← hx, mul_comm]
        exact hlt a ha b hb
      exact Nat.lt_of_mul_lt_mul_left h2
    have hylt : y < A.card := by
      have h2 : a.gcd b * y < a.gcd b * A.card := by
        rw [← hy, mul_comm, Nat.gcd_comm]
        exact hlt b hb a ha
      exact Nat.lt_of_mul_lt_mul_left h2
    have hcopg : A.card.gcd (a.gcd b) = 1 := by
      have h1 : Nat.Coprime A.card (a.gcd b) := by
        rw [Nat.Prime.coprime_iff_not_dvd hpr]
        intro h
        exact hnd a ha (h.trans (Nat.gcd_dvd_left a b))
      exact h1
    have hmod : a.gcd b * x ≡ a.gcd b * y [MOD A.card] := by
      rw [← hx, ← hy]
      exact heq
    have hxy : x ≡ y [MOD A.card] := Nat.ModEq.cancel_left_of_coprime hcopg hmod
    have hxy' : x = y := by
      unfold Nat.ModEq at hxy
      rwa [Nat.mod_eq_of_lt hxlt, Nat.mod_eq_of_lt hylt] at hxy
    apply hab
    calc a = a.gcd b * x := hx
      _ = a.gcd b * y := by rw [hxy']
      _ = b := hy.symm
  · obtain ⟨a, ha, b, hb, hle⟩ :=
      hcomp A hA hne hg hpr (fun a ha b hb => (hlt a ha b hb).le) hpp
    exact absurd hle (not_le.mpr (hcon a ha b hb))
