module
public import Mathlib.Data.Finsupp.Basic
public import Mathlib.Data.Finsupp.Defs
public import Mathlib.Data.List.NodupEquivFin
public import Mathlib.Data.Finset.Max
public import Mathlib.Algebra.BigOperators.Group.Finset.Basic
public import Mathlib.Basic.Real.Basic
public import Mathlib.Data.Finset.Interval
public import Mathlib.Data.Nat.Choose.Sum
public import Mathlib.Combinatorics.Enumerative.IncidenceAlgebra
public import Mathlib.LinearAlgebra.FiniteDimensional.Basic
public import Mathlib.Tactic

@[expose] public section

/-! The independent full finite random-utility challenge. -/
namespace Falmagne

variable {X : Type*} [Fintype X] [DecidableEq X]

def IsRanking (l : List X) : Prop :=
  l.Nodup ∧ l.toFinset = Finset.univ

/-- The alternatives weakly below `x` in the best-to-worst list. -/
def lowerContour (l : List X) (x : X) : Finset X :=
  l.toFinset.filter fun y => l.idxOf x ≤ l.idxOf y

/-- Deterministic menu choice; the empty menu has no chosen alternative. -/
noncomputable def rankingChoice (l : List X) (A : Finset X) (x : X) : ℝ :=
  if x ∈ A ∧ A ⊆ lowerContour l x then 1 else 0

abbrev RankingLaw (X : Type*) := List X →₀ ℝ

/-- Probability laws supported on complete strict rankings. -/
def IsRankingLaw (w : RankingLaw X) : Prop :=
  (∀ l, 0 ≤ w l) ∧
  (∀ l ∈ w.support, IsRanking l) ∧
  w.sum (fun _ a => a) = 1

/-- A stochastic choice rule on all menus; the empty menu is zero. -/
def IsChoiceRule (p : Finset X → X → ℝ) : Prop :=
  (∀ A x, 0 ≤ p A x) ∧
  (∀ A x, x ∉ A → p A x = 0) ∧
  (∀ A, A.Nonempty → ∑ x ∈ A, p A x = 1)

/-- All observed menu probabilities are generated by the same ranking law. -/
def Represents (w : RankingLaw X) (p : Finset X → X → ℝ) : Prop :=
  ∀ A x, p A x = w.sum (fun l a => a * rankingChoice l A x)


end Falmagne

namespace EconomicsNextProof
open Finset
variable {X : Type*} [Fintype X] [DecidableEq X]

noncomputable def upperSum (f : Finset X → ℝ) (A : Finset X) : ℝ :=
  ∑ B ∈ Finset.univ.filter (fun B : Finset X => A ⊆ B), f B

noncomputable def upperMobius (f : Finset X → ℝ) (A : Finset X) : ℝ :=
  ∑ B ∈ Finset.univ.filter (fun B : Finset X => A ⊆ B),
    (-1 : ℝ) ^ (B \ A).card * f B


end EconomicsNextProof

namespace Falmagne
variable {X : Type*} [Fintype X] [DecidableEq X]
noncomputable def blockMarschak (p : Finset X → X → ℝ) (x : X) (A : Finset X) : ℝ :=
  EconomicsNextProof.upperMobius (fun B => p B x) A

variable [Nonempty X]
def BlockMarschakNonnegative (p : Finset X → X → ℝ) : Prop :=
  ∀ x A, x ∈ A → 0 ≤ blockMarschak p x A

def RandomUtilityRepresentable (p : Finset X → X → ℝ) : Prop :=
  ∃ w : RankingLaw X, IsRankingLaw w ∧ Represents w p

/-- Full Falmagne–Block–Marschak equivalence, with no cardinality bound. -/
theorem falmagne_blockMarschak {p : Finset X → X → ℝ} (hp : IsChoiceRule p) :
    RandomUtilityRepresentable p ↔ BlockMarschakNonnegative p := by
  sorry

end Falmagne
