"""The gate's build layout (F01-Q2, Q4): stage a node and its dependency closure as modules.

``<workdir>/src/Nodes/<id>/{Statement,Proof,Witness}.lean`` are copies of the node's files;
``Context.lean`` is *generated* — it imports each declared dep's ``Nodes.«dep».Proof`` — so the
proof compiles against the deps' merged proofs, never against the repo's sorry-bodied
signatures (which step 8 checks textually instead). Deps are staged recursively and every one of
them must already carry a ``Proof.lean``; a node whose deps are unproved is blocked (F03) and
cannot pass steps 4-8.
"""

from __future__ import annotations

import shutil
from dataclasses import dataclass, field
from pathlib import Path

from opn_gate import layout, schemas
from opn_gate.diagnostic import Diagnostic

NODE_FILES: tuple[str, ...] = ("Statement.lean", "Proof.lean", "Witness.lean")


@dataclass(frozen=True)
class Staged:
    root: Path  # the source root: modules are paths relative to it
    build: Path  # where oleans go, mirroring the module paths
    order: tuple[str, ...]  # node ids in build order (deps first, the node last)
    problems: tuple[Diagnostic, ...] = field(default_factory=tuple)

    def node_dir(self, node_id: str) -> Path:
        return self.root / "Nodes" / node_id

    def rel(self, node_id: str, stem: str) -> Path:
        return Path("Nodes") / node_id / f"{stem}.lean"


def generated_context(deps: list[str]) -> str:
    lines = [f"import {layout.node_module(dep, 'Proof')}" for dep in deps]
    body = "\n".join(lines) + ("\n" if lines else "")
    return (
        "-- Generated by the gate (F01-Q4): the declared deps' merged proofs stand in for the\n"
        "-- repo's sorry-bodied Context.lean, whose signatures step 8 checks against them.\n" + body
    )


def stage(node: layout.Node, workdir: Path, *, proof_override: Path | None = None) -> Staged:
    """Copy the node and its dependency closure into the build layout. ``proof_override`` is a
    partial's assembly (F07-R5): it is staged as the node's own ``Proof.lean``, since it declares
    the statement's theorem and is built and replayed exactly as a proof is."""
    root = workdir / "src"
    build = workdir / "build"
    problems: list[Diagnostic] = []
    order: list[str] = []
    seen: set[str] = set()
    nodes_dir = node.path.parent

    def deps_of(node_dir: Path) -> list[str]:
        try:
            meta = schemas.load_yaml(node_dir / "META.yaml")
        except schemas.SchemaError as exc:
            problems.append(Diagnostic("dep-meta", f"{node_dir.name}: {exc}"))
            return []
        raw = meta.get("deps")
        return [str(d) for d in raw] if isinstance(raw, list) else []

    def visit(node_id: str, chain: tuple[str, ...]) -> None:
        if node_id in seen:
            return
        if node_id in chain:
            problems.append(
                Diagnostic("dep-cycle", "dependency cycle: " + " -> ".join((*chain, node_id)))
            )
            return
        src = nodes_dir / node_id
        if not src.is_dir():
            problems.append(Diagnostic("dep-missing", f"declared dep {node_id!r} is not a node"))
            return
        deps = deps_of(src)
        for dep in deps:
            visit(dep, (*chain, node_id))
        if node_id != node.node_id and not (src / "Proof.lean").is_file():
            problems.append(
                Diagnostic(
                    "dep-unproved",
                    f"dep {node_id!r} has no merged Proof.lean; this node is blocked until it does",
                    {"dep": node_id},
                )
            )
        dest = root / "Nodes" / node_id
        dest.mkdir(parents=True, exist_ok=True)
        for name in NODE_FILES:
            if (src / name).is_file():
                shutil.copy(src / name, dest / name)
        if node_id == node.node_id and proof_override is not None:
            shutil.copy(proof_override, dest / "Proof.lean")
        (dest / "Context.lean").write_text(generated_context(deps), encoding="utf-8")
        (build / "Nodes" / node_id).mkdir(parents=True, exist_ok=True)
        seen.add(node_id)
        order.append(node_id)

    visit(node.node_id, ())
    return Staged(root=root, build=build, order=tuple(order), problems=tuple(problems))
