import Mathlib
#check @Nat.exists_prime_lt_and_le_two_mul
#check @primorial_le_four_pow
#check @Nat.primeCounting
#check @Chebyshev.theta
#check @Chebyshev.psi
#check @Chebyshev.theta_le_log4_mul_x
#check @Chebyshev.psi_le_const_mul_self
#check @Chebyshev.primeCounting_le_const_mul_div_log
#check @Chebyshev.theta_ge
#check @Nat.primeCounting_le_const_mul_div_log
#check @PrimeNumberTheorem
#check @Nat.Prime.exists_prime_between
#check @Nat.four_pow_lt_mul_centralBinom
#check @Nat.primeCounting'_add_le
#check @Nat.smoothNumbers
#check @Nat.smoothNumbersUpTo_card_le
#check @Nat.card_multiples
#check @ArithmeticFunction.vonMangoldt
#check @Nat.bertrand
#check @Chebyshev.eventually_primeCounting_le
#check @Chebyshev.primeCounting_eq_theta_div_log_add_integral
